import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const core=require('../www/etp-core-contract.js');
const profileAuthority=require('../www/etp-profile-authority.js');
const registryApi=require('../www/etp-control-registry.js');
const readerApi=require('../www/etp-verified-reader.js');
const lifecycle=require('../www/etp-store-lifecycle-policy.js');
const profile=require('../www/etp-retail-profile.js');
const H='a'.repeat(64),scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30'},authorityBinding=profileAuthority.authorize({storeCode:'WLMHW',purpose:'PRODUCTION',profileVersion:profileAuthority.PROFILE_VERSION,parserVersion:profileAuthority.PARSER_VERSION}).binding;
const tenderIdentity={contractVersion:'ETP_TENDER_DICTIONARY_V1',versionId:'retail-etp-tender-v1',effectiveAt:'2026-08-24T00:00:00.000Z'};
function reports(){return Object.fromEntries(core.REPORTS.map(id=>[id,{sourceSha256:H}]));}
function declaration(){return{confirmed:true,confirmedByRole:'OWNER',reports:Object.fromEntries(core.REPORTS.map(id=>[id,{status:'COMPLETE'}]))};}
const enrichments={R003:{status:'FAIL',differenceCount:2},R013:{status:'FAIL',differenceCount:1},paymentType25:{status:'QUARANTINED',rowCount:3,persisted:false}};
function accepted(){let x=lifecycle.create(scope,'etp_'+'1'.repeat(32)).lifecycle;for(const event of ['PREFLIGHT_PASS','PARSE_PASS','POLICY_PASS','BEGIN_STAGING','STAGE_COMPLETE'])x=lifecycle.transition(x,event).lifecycle;const manifest={scopeKey:x.scopeKey,generationId:x.candidateGenerationId,authority:authorityBinding,tenderDictionary:tenderIdentity,reports:core.REPORTS.map(reportId=>({reportId,sourceSha256:H,headerSignatureSha256:H,rowCount:1}))};x=lifecycle.attachManifest(x,manifest).lifecycle;x=lifecycle.transition(x,'RECONCILE_PASS').lifecycle;x=lifecycle.transition(x,'REQUEST_CONFIRMATION').lifecycle;return lifecycle.publish(x).lifecycle;}
test('India business date does not use UTC midnight',()=>{assert.equal(core.indiaDate(Date.UTC(2026,7,8,20,0)),'2026-08-09');});
test('coverage requires an owner/admin declaration for every exact report',()=>{assert.equal(core.coverage(scope,reports(),declaration()).ok,true);assert.equal(core.coverage(scope,reports(),{...declaration(),confirmed:false}).code,'ETP_COVERAGE_CONFIRMATION_REQUIRED');const partial=declaration();partial.reports.R013={status:'INTERNAL_GAP'};assert.equal(core.coverage(scope,reports(),partial).code,'ETP_COVERAGE_INCOMPLETE');});
test('receipt registry stores metadata and bounded history without facts',()=>{const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},made=registryApi.create({storage,core});const life=accepted(),coverage=core.coverage(scope,reports(),declaration()).coverage,created=core.createReceipt({lifecycle:life,reconciliation:{status:'PASS',enrichments},coverage,authority:authorityBinding,tenderDictionary:tenderIdentity,publishedAtMs:Date.UTC(2026,7,9)});assert.equal(created.ok,true);assert.equal(made.registry.saveReceipt(created.receipt).ok,true);assert.equal(made.registry.getReceipt(life.scopeKey).receipt.activeGenerationId,life.activeGenerationId);assert.equal(created.receipt.profileAuthority.evidenceIdentity,authorityBinding.evidenceIdentity);const raw=values.get(registryApi.KEY);assert.doesNotMatch(raw,/rows|payload|workbook|customer/i);});
test('verified reader binds active native generation and report-specific fields',async()=>{const life=accepted(),coverage=core.coverage(scope,reports(),declaration()).coverage,receipt=core.createReceipt({lifecycle:life,reconciliation:{status:'PASS',enrichments},coverage,authority:authorityBinding,tenderDictionary:tenderIdentity,publishedAtMs:Date.UTC(2026,7,9)}).receipt;const nativeStore={readStatus:async()=>({ok:true,status:{state:'ACCEPTED',restoreFence:false,activeGenerationId:life.activeGenerationId}}),readFacts:async(_s,r)=>({ok:true,request:r})},registry={getReceipt:()=>({ok:true,receipt})},made=readerApi.create({core,profile,nativeStore,registry,lifecyclePolicy:lifecycle});assert.equal(made.ok,true);assert.equal((await made.reader.read(scope,{reportId:'R022',fields:['invoice_number'],cursor:null,limit:10})).ok,true);assert.equal((await made.reader.read(scope,{reportId:'R022',fields:['item_number'],cursor:null,limit:10})).code,'ETP_VERIFIED_PROJECTION_INVALID');assert.equal((await made.reader.read(scope,{reportId:'R022',fields:['payment_type25_amount'],cursor:null,limit:10})).code,'ETP_VERIFIED_PROJECTION_INVALID');nativeStore.readStatus=async()=>({ok:true,status:{state:'REIMPORT_REQUIRED',restoreFence:true,activeGenerationId:null}});assert.equal((await made.reader.read(scope,{reportId:'R022',fields:['invoice_number'],cursor:null,limit:10})).code,'ETP_VERIFIED_GENERATION_UNAVAILABLE');});
