import test from 'node:test';
import assert from 'node:assert/strict';
import api from '../www/etp-foundation-status.js';

const generation='etp_'+'a'.repeat(32);
const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30',scopeKey:'WLMHW|2026-27|2026-04-01..2026-04-30'};
function coverage(status='COMPLETE'){return Object.fromEntries(api.REPORTS.map(id=>[id,{status,zeroActivityConfirmed:status==='COMPLETE_WITH_ZERO_ACTIVITY'}]));}
function receipt(){return{activeGenerationId:generation,reconciliationStatus:'PASS',coverage:coverage(),exceptions:{R003:{status:'PASS',differenceCount:0},R013:{status:'PASS',differenceCount:0},paymentType25:{status:'QUARANTINED',rowCount:0,persisted:false}},profileVersion:'retail-etp-core-v1',ruleVersion:'rec_002_v1',publishedAt:'2026-08-24T10:15:30.000Z'};}
function input(){return{contractVersion:api.VERSION,scope:{...scope},factStoreAvailable:true,nativeStatus:{state:'ACCEPTED',restoreFence:false,activeGenerationId:generation},receipt:receipt()};}

test('publishes immutable sanitized ETP Foundation v1 READY metadata',()=>{const out=api.evaluate(input());assert.deepEqual(out,{ok:true,contractVersion:'ETP_FOUNDATION_V1',status:'READY',showValues:true,reasons:[],warnings:[],scope,activeGenerationId:generation,verifiedThrough:'2026-04-30',publishedAt:'2026-08-24T10:15:30.000Z'});assert.equal(Object.isFrozen(out),true);assert.equal(Object.isFrozen(out.scope),true);assert.doesNotMatch(JSON.stringify(out),/filename|workbook|rows|customer/i);});
test('noncritical exceptions, zero activity and PAYMENTTYPE25 are explicit warnings',()=>{const value=input();value.receipt.coverage.R003={status:'COMPLETE_WITH_ZERO_ACTIVITY',zeroActivityConfirmed:true};value.receipt.exceptions.R013={status:'FAIL',differenceCount:2};value.receipt.exceptions.paymentType25.rowCount=7;const out=api.evaluate(value);assert.equal(out.status,'READY_WITH_WARNINGS');assert.equal(out.showValues,true);assert.deepEqual(out.warnings,['PAYMENTTYPE25_QUARANTINED','R003_ZERO_ACTIVITY_CONFIRMED','R013_EXCEPTIONS_OPEN']);});
test('missing or mismatched accepted generation and REC-002 failure are NOT_READY and hide values',()=>{for(const mutate of [v=>{v.factStoreAvailable=false;},v=>{v.nativeStatus.restoreFence=true;v.nativeStatus.state='REIMPORT_REQUIRED';v.nativeStatus.activeGenerationId=null;},v=>{v.nativeStatus.activeGenerationId='etp_'+'b'.repeat(32);},v=>{v.receipt.reconciliationStatus='FAIL';}]){const value=input();mutate(value);const out=api.evaluate(value);assert.equal(out.ok,true);assert.equal(out.status,'NOT_READY');assert.equal(out.showValues,false);assert.equal(out.activeGenerationId,null);assert.equal(out.verifiedThrough,null);}});
test('null receipt is a sanitized NOT_READY state',()=>{const value=input();value.receipt=null;value.nativeStatus={state:'EMPTY',restoreFence:false,activeGenerationId:null};const out=api.evaluate(value);assert.equal(out.status,'NOT_READY');assert.deepEqual(out.reasons,['RECEIPT_REQUIRED','VERIFIED_GENERATION_UNAVAILABLE']);});
test('malformed scopes, coverage, counts and extra or hostile keys fail closed',()=>{const cases=[];let value=input();value.scope.scopeKey=scope.scopeKey.replace('WLMHW','HEMW');cases.push(value);value=input();value.receipt.coverage.R003.status='PARTIAL_END';cases.push(value);value=input();value.receipt.exceptions.R003.differenceCount=250001;cases.push(value);value=input();value.filename='private.xlsx';cases.push(value);value=input();value.receipt=Object.assign(Object.create({constructor:'x'}),value.receipt);cases.push(value);for(const hostile of cases)assert.equal(api.evaluate(hostile).code,'ETP_FOUNDATION_INPUT_INVALID');});
