import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import api from '../www/etp-query-contract.js';

const cursor='cur_'+ 'A'.repeat(32),generation='etp_'+'a'.repeat(32),scopeKey='WLMHW|2026-27|2026-04-01..2026-04-30';
function request(){return{contractVersion:api.VERSION,reportId:'R025',fields:['invoice_number','net_amount','brand'],filters:[{field:'brand',operator:'IN',value:[' Titan ','Fastrack','Titan']},{field:'invoice_date',operator:'gte',value:'2026-04-01'}],sort:[{field:'invoice_date',direction:'asc'},{field:'invoice_number',direction:'ASC'}],limit:100,cursor:null};}

test('canonicalizes an exact bounded query and produces deterministic signature input',()=>{const one=api.canonicalize(request()),twoRequest=request();twoRequest.filters.reverse();const two=api.canonicalize(twoRequest);assert.equal(one.ok,true);assert.equal(one.signatureInput,two.signatureInput);assert.deepEqual(one.query.filters.find(item=>item.field==='brand').value,['Fastrack','Titan']);assert.equal(Object.isFrozen(one.query),true);assert.equal(Object.isFrozen(one.query.filters),true);assert.doesNotMatch(one.signatureInput,/filename|workbook|customer|mobile/i);});
test('per-report projections filters and sorts are exact frozen allowlists',()=>{assert.deepEqual(Object.keys(api.PROJECTIONS),['R003','R013','R022','R025']);assert.equal(Object.isFrozen(api.PROJECTIONS.R025),true);let value=request();value.fields=['customer_name'];assert.equal(api.canonicalize(value).code,'ETP_QUERY_PROJECTION_INVALID');value=request();value.filters=[{field:'customer_name',operator:'EQ',value:'Private'}];assert.equal(api.canonicalize(value).code,'ETP_QUERY_FILTER_INVALID');value=request();value.sort=[{field:'customer_name',direction:'ASC'}];assert.equal(api.canonicalize(value).code,'ETP_QUERY_SORT_INVALID');});
test('verified analytics date and receipt projections are canonical query fields',()=>{for(const reportId of Object.keys(api.PROJECTIONS)){const value=request();value.reportId=reportId;value.fields=['invoice_date'];value.filters=[];value.sort=[];assert.equal(api.canonicalize(value).ok,true,reportId);}const receipt=request();receipt.reportId='R022';receipt.fields=['invoice_date','invoice_number'];receipt.filters=[];receipt.sort=[];assert.equal(api.canonicalize(receipt).ok,true);});
test('R013 invoice identity is projectable and sortable but does not widen filter authority',()=>{let value=request();value.reportId='R013';value.fields=['invoice_number','cro_number','net_amount'];value.filters=[];value.sort=[{field:'invoice_number',direction:'ASC'}];assert.equal(api.canonicalize(value).ok,true);value.filters=[{field:'invoice_number',operator:'EQ',value:'INV-1'}];assert.equal(api.canonicalize(value).code,'ETP_QUERY_FILTER_INVALID');});
test('hostile prototypes, extra keys and constructor fields fail closed',()=>{let value=request();value=Object.assign(Object.create({polluted:true}),value);assert.equal(api.canonicalize(value).code,'ETP_QUERY_INVALID');value=request();value.rawFacts=[];assert.equal(api.canonicalize(value).code,'ETP_QUERY_INVALID');value=request();value.filters=[Object.assign(Object.create({polluted:true}),{field:'brand',operator:'EQ',value:'Titan'})];assert.equal(api.canonicalize(value).code,'ETP_QUERY_FILTER_INVALID');value=request();value.fields=['constructor'];assert.equal(api.canonicalize(value).code,'ETP_QUERY_PROJECTION_INVALID');});
test('filter, text, IN, sort, projection, limit and cursor bounds fail closed',()=>{let value=request();value.filters=Array.from({length:api.MAX_FILTERS+1},()=>({field:'brand',operator:'EQ',value:'x'}));assert.equal(api.canonicalize(value).code,'ETP_QUERY_FILTER_INVALID');value=request();value.filters=[{field:'brand',operator:'EQ',value:'x'.repeat(api.MAX_TEXT+1)}];assert.equal(api.canonicalize(value).code,'ETP_QUERY_FILTER_INVALID');value=request();value.filters=[{field:'brand',operator:'IN',value:Array.from({length:api.MAX_IN_VALUES+1},(_,i)=>'x'+i)}];assert.equal(api.canonicalize(value).code,'ETP_QUERY_FILTER_INVALID');value=request();value.sort=Array.from({length:api.MAX_SORTS+1},()=>({field:'brand',direction:'ASC'}));assert.equal(api.canonicalize(value).code,'ETP_QUERY_SORT_INVALID');value=request();value.limit=201;assert.equal(api.canonicalize(value).code,'ETP_QUERY_LIMIT_INVALID');value=request();value.cursor={chunkIndex:0,rowOffset:0};assert.equal(api.canonicalize(value).code,'ETP_QUERY_CURSOR_INVALID');});
test('opaque token validation makes no crypto or coordinate claim',()=>{assert.equal(api.isOpaqueToken(cursor),true);assert.equal(api.isOpaqueToken('cur_short'),false);assert.equal(api.isOpaqueToken({chunkIndex:0,rowOffset:0}),false);const source=fs.readFileSync(new URL('../www/etp-query-contract.js',import.meta.url),'utf8');assert.doesNotMatch(source,/\b(?:btoa|atob|HMAC)\b|crypto\.|chunkIndex|rowOffset/i);});
test('cursor binding is immutable and binds scope generation report and query signature input',()=>{const query=api.canonicalize(request()),value={contractVersion:api.VERSION,token:cursor,scopeKey,generationId:generation,reportId:'R025',querySignatureInput:query.signatureInput},checked=api.validateCursorBinding(value);assert.equal(checked.ok,true);assert.equal(Object.isFrozen(checked.binding),true);const context={scopeKey,generationId:generation,reportId:'R025',querySignatureInput:query.signatureInput};assert.equal(api.cursorBindingMatches(checked.binding,context),true);for(const change of [{scopeKey:scopeKey.replace('WLMHW','HEMW')},{generationId:'etp_'+'b'.repeat(32)},{reportId:'R022'},{querySignatureInput:query.signatureInput+'x'}])assert.equal(api.cursorBindingMatches(checked.binding,{...context,...change}),false);});
test('malformed cursor bindings and contexts fail closed',()=>{const query=api.canonicalize(request()),base={contractVersion:api.VERSION,token:cursor,scopeKey,generationId:generation,reportId:'R025',querySignatureInput:query.signatureInput};for(const change of [{token:'raw:0:1'},{scopeKey:'ALL|2026-27|x'},{generationId:'old'},{reportId:'R999'},{querySignatureInput:'x'.repeat(api.MAX_SIGNATURE_INPUT+1)},{filename:'private.xlsx'}])assert.equal(api.validateCursorBinding({...base,...change}).code,'ETP_CURSOR_BINDING_INVALID');assert.equal(api.cursorBindingMatches(base,Object.assign(Object.create({polluted:true}),{scopeKey,generationId:generation,reportId:'R025',querySignatureInput:query.signatureInput})),false);});
