import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),api=require('../www/etp-verified-presentation.js');
const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30'};
function row(id,n=1){if(id==='R022')return{transaction_type_raw:'INV',invoice_quantity:'1',net_value:String(n),cash_amount:String(n),card_amount:'0',bhim_upi_amount:'0',phonepe_amount:'0',paytm_amount:'0',razorpay_amount:'0',bharatpe_amount:'0',cheque_amount:'0',others_amount:'0',payment_type24_amount:'0'};if(id==='R025')return{invoice_number:String(n),transaction_type_raw:'INV',quantity:'1',net_amount:String(n),brand:'Titan',cluster:'A',gender:'U',scheme_discount:'1',user_discount:'0',tax_amount:'1'};if(id==='R013')return{transaction_type_raw:'INV',quantity:'1',net_amount:String(n),cro_number:'101'};return{transaction_type_raw:'INV',net_amount:String(n),scheme_discount:'1',user_discount:'0'};}
function gateway(makePage){return{async inspectScope(){return{ok:true,scope,status:{state:'ACCEPTED'},currentReceipt:{reconciliationStatus:'PASS',ruleVersion:'rec_002_v1',exceptions:{R003:{status:'PASS',differenceCount:0},R013:{status:'FAIL',differenceCount:2},paymentType25:{status:'QUARANTINED',rowCount:9,persisted:false}}},history:[]};},async readVerified(_scope,request){return makePage(request);}};}
test('binds the presentation controller to the governed manifest identity',()=>{const manifest=require('../www/module-manifest.js'),asset=manifest.getShared('etp-verified-presentation'),bytes=fs.readFileSync(new URL('../www/etp-verified-presentation.js',import.meta.url)),moduleHtml=fs.readFileSync(new URL('../www/modules/etp/index.html',import.meta.url),'utf8');assert.deepEqual(asset,{id:'etp-verified-presentation',version:1,file:'etp-verified-presentation.js',bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});assert.match(moduleHtml,/<script src="\.\.\/\.\.\/etp-verified-presentation\.js"><\/script>/);});
test('publishes exact privacy-safe projections and conservative ceilings',()=>{assert.equal(api.PAGE_LIMIT,200);assert.equal(api.MAX_PAGES,100);assert.equal(api.MAX_ROWS,20000);assert.deepEqual(Object.keys(api.PROJECTIONS),['R003','R013','R022','R025']);let all=Object.values(api.PROJECTIONS).flat();assert.equal(all.some(x=>/(?:^|_)(?:customer|mobile|phone|email|address|name|payment_type25)(?:$|_)/i.test(x)),false);});
test('aggregates signed measures without retaining source rows',()=>{let acc=api.create('R022');assert.equal(api.append(acc,[row('R022',10),{...row('R022',3),transaction_type_raw:'SR'}]).ok,true);let out=api.finish(acc);assert.equal(out.rowCount,2);assert.equal(out.moneyUnits.net_value,700);assert.equal(out.quantityUnits,0);assert.equal('rows' in out,false);});
test('loads all four reports through bounded gateway pages and exposes quarantine metadata only',async()=>{let calls=[];let result=await api.load(gateway(req=>{calls.push(req);return{ok:true,page:{rows:[row(req.reportId)],hasMore:false,nextCursor:null}};}),scope);assert.equal(result.ok,true);assert.equal(calls.length,4);assert.ok(calls.every(x=>x.limit===200&&x.cursor===null));assert.equal(result.receipt.exceptions.paymentType25.rowCount,9);assert.equal(JSON.stringify(result).includes('customer'),false);});
test('refuses repeated cursors and never loops',async()=>{let calls=0;let result=await api.load(gateway(req=>{calls++;return{ok:true,page:{rows:[row(req.reportId)],hasMore:true,nextCursor:{chunkIndex:0,rowOffset:1}}};}),scope);assert.equal(result.code,'ETP_VIEW_CURSOR_REPEATED');assert.equal(calls,2);});
test('stops before a 101st page or more than 20000 rows',async()=>{let index=0;let result=await api.load(gateway(req=>{let next={chunkIndex:Math.floor(index/500),rowOffset:index%500};index++;return{ok:true,page:{rows:[row(req.reportId)],hasMore:true,nextCursor:next}};}),scope);assert.equal(result.code,'ETP_VIEW_REFRESH_LIMIT_EXCEEDED');assert.equal(index,100);});
test('rejects overlarge pages, unknown transactions and unexpected fields',()=>{let acc=api.create('R003');assert.equal(api.append(acc,Array.from({length:201},()=>row('R003'))).code,'ETP_VIEW_PAGE_INVALID');assert.equal(api.append(api.create('R003'),[{...row('R003'),transaction_type_raw:'OTHER'}]).code,'ETP_VIEW_TRANSACTION_INVALID');assert.equal(api.append(api.create('R003'),[{...row('R003'),secret:'x'}]).code,'ETP_VIEW_ROW_INVALID');});
