import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url),api=require('../www/etp-verified-presentation.js');
const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30'};
const fullScope={...scope,scopeKey:'WLMHW|2026-27|2026-04-01..2026-04-30'};
const receipt={reconciliationStatus:'PASS',ruleVersion:'rec_002_v1',exceptions:{R003:{status:'PASS',differenceCount:0},R013:{status:'FAIL',differenceCount:2},paymentType25:{status:'QUARANTINED',rowCount:9,persisted:false}}};
function summary(id){const moneyUnits={};if(id==='R022')moneyUnits.net_value=100;if(id!=='R022')moneyUnits.net_amount=100;return{reportId:id,rowCount:1,quantityUnits:id==='R003'?0:1000,moneyUnits,groups:id==='R025'?[{label:'Titan',rowCount:1,netUnits:100}]:[]};}
function model(selected=fullScope){return{ok:true,scope:selected,status:{contractVersion:'ETP_FOUNDATION_V1',status:'READY_WITH_WARNINGS',showValues:true,reasons:[],warnings:['R013_EXCEPTIONS_OPEN'],verifiedThrough:selected.periodEnd,publishedAt:'2026-05-01T00:00:00.000Z'},receipt,history:[],summaries:Object.fromEntries(['R003','R013','R022','R025'].map(id=>[id,summary(id)])),pages:4,rowCount:4};}
function facade(load=async selected=>model({...selected,scopeKey:[selected.storeCode,selected.financialYear,selected.periodStart+'..'+selected.periodEnd].join('|')})){return Object.freeze({listScopes(){return{ok:true,scopes:[]};},inspectScope(){return{ok:true};},loadSummary:load});}
test('presentation consumes only the parent-owned summary facade and never requests facts',()=>{const source=fs.readFileSync(new URL('../www/etp-verified-presentation.js',import.meta.url),'utf8'),moduleHtml=fs.readFileSync(new URL('../www/modules/etp/index.html',import.meta.url),'utf8');assert.match(source,/readFacade\.loadSummary\(scope\)/);assert.doesNotMatch(source,/readVerified\s*\(/);assert.doesNotMatch(source,/runtime\.|storage\.|readFacts/);assert.match(moduleHtml,/<script src="\.\.\/\.\.\/etp-verified-presentation\.js"><\/script>/);});
test('loads frozen sanitized summaries without receiving rows or cursors',async()=>{let calls=0;const result=await api.load(facade(async()=>{calls++;return model();}),scope);assert.equal(result.ok,true);assert.equal(calls,1);assert.equal(result.summaries.R025.groups[0].label,'Titan');assert.equal(Object.isFrozen(result.summaries),true);assert.doesNotMatch(JSON.stringify(result),/"(?:rows|cursor|page)"/i);});
test('rejects raw pages, cursors, unexpected summaries and unsafe aggregate shapes',async()=>{for(const mutate of [value=>{value.rows=[];},value=>{value.cursor='cur_x';},value=>{value.summaries.R025.secret=1;},value=>{value.summaries.R025.groups[0].label='x'.repeat(81);},value=>{value.summaries.R025.moneyUnits.net_amount=Infinity;}]){const value=model();mutate(value);assert.equal((await api.load(facade(async()=>value),scope)).code,'ETP_VIEW_SUMMARY_INVALID');}});
test('gateway failures are reduced to stable presentation failures',async()=>{assert.equal((await api.load(facade(async()=>({ok:false,code:'ETP_ACCESS_DENIED'})),scope)).code,'ETP_ACCESS_DENIED');assert.equal((await api.load(facade(async()=>{throw new Error('private');}),scope)).code,'ETP_VIEW_SUMMARY_FAILED');assert.equal((await api.load({},scope)).code,'ETP_VIEW_GATEWAY_UNAVAILABLE');});
test('uses only an injected active published scope and snapshots it',()=>{let active={...scope};let selected=api.injectedScope({getScope:()=>active});assert.deepEqual(selected,scope);active.storeCode='HEMW';assert.equal(selected.storeCode,'WLMHW');assert.equal(api.injectedScope({getScope:()=>null}),null);assert.equal(api.injectedScope({getScope(){throw new Error('revoked');}}),null);});
test('queues the newest active scope when selection changes during a refresh',async()=>{class Node{constructor(doc){this.ownerDocument=doc;this.children=[];this.disabled=false;}get firstChild(){return this.children[0]||null;}appendChild(node){this.children.push(node);return node;}removeChild(node){this.children.splice(this.children.indexOf(node),1);}addEventListener(){}}const doc={createElement(){return new Node(doc);}},content=new Node(doc),exceptions=new Node(doc),button=new Node(doc),root={querySelector(value){return value.includes('verified-content')?content:value.includes('exceptions-content')?exceptions:null;},querySelectorAll(){return[button];}};let active={...scope},release,seen=[];const wait=new Promise(resolve=>{release=resolve;}),readFacade=facade(async selected=>{seen.push(selected.storeCode);if(seen.length===1)await wait;return model({...selected,scopeKey:[selected.storeCode,selected.financialYear,selected.periodStart+'..'+selected.periodEnd].join('|')});});const mounted=api.mount(root,readFacade,{getScope:()=>active}),first=mounted.refresh();active={...scope,storeCode:'HEMW'};assert.equal((await mounted.refresh()).code,'ETP_VIEW_BUSY');release();assert.equal((await first).ok,true);assert.deepEqual(seen,['WLMHW','HEMW']);});
