import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),api=require('../www/etp-import-history.js');
const scopeKey='WLMHW|2026-27|2026-04-01..2026-04-30';
function event(index=1,override={}){return{contractVersion:api.VERSION,eventId:'batch:'+index,scopeKey,storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30',outcome:'VALIDATED',warningCodes:[],counts:{sourceCount:10,selectedCount:8,excludedCount:2},actorId:'owner:01',occurredAt:'2026-08-24T10:00:'+String(index%60).padStart(2,'0')+'Z',digestRefs:['sha256:'+String(index%10).repeat(64)],...override};}
function memory(initial=null){let value=initial,writes=0;return{getItem:key=>key===api.KEY?value:null,setItem(_key,next){writes++;value=next;},value:()=>value,writes:()=>writes};}
test('validates immutable metadata-only events for every controlled outcome',()=>{for(const outcome of api.OUTCOMES){const checked=api.validateEvent(event(1,{outcome}));assert.equal(checked.ok,true,outcome);assert.equal(Object.isFrozen(checked.event),true);assert.equal(Object.isFrozen(checked.event.counts),true);assert.doesNotMatch(JSON.stringify(checked),/filename|fileLabel|path|workbook|"rows"|customer|mobile|phone|email|address/i);}});
test('rejects filenames, raw material, PII, bad counts, unsafe digests and hostile prototypes',()=>{const cases=[];let value=event();value.filename='R022.xlsx';cases.push(value);value=event();value.rows=[];cases.push(value);value=event();value.customerName='Private';cases.push(value);value=event();value.counts={sourceCount:10,selectedCount:9,excludedCount:2};cases.push(value);value=event();value.digestRefs=['sha256:bad'];cases.push(value);value=Object.assign(Object.create({polluted:true}),event());cases.push(value);for(const item of cases)assert.equal(api.validateEvent(item).ok,false);});
test('stores bounded per-scope and global history with deterministic ordering',()=>{const store=memory(),made=api.create({storage:store});assert.equal(made.ok,true);for(let i=1;i<=api.MAX_PER_SCOPE+5;i++)assert.equal(made.history.append(event(i)).ok,true);const listed=made.history.list(scopeKey,api.MAX_PER_SCOPE);assert.equal(listed.events.length,api.MAX_PER_SCOPE);assert.equal(listed.events[0].occurredAt>listed.events.at(-1).occurredAt,true);assert.equal(JSON.parse(store.value()).events.length,api.MAX_PER_SCOPE);assert.equal(Object.isFrozen(listed.events),true);});
test('duplicate event IDs are idempotent but historical changes are refused',()=>{const store=memory(),history=api.create({storage:store}).history,original=event(1);assert.deepEqual(history.append(original).changed,true);assert.deepEqual(history.append(original).changed,false);assert.equal(history.append(event(1,{outcome:'ACCEPTED'})).code,'ETP_IMPORT_HISTORY_EVENT_CONFLICT');assert.equal(store.writes(),1);});
test('corrupt entries are ignored deterministically without blocking valid history',()=>{const valid=api.validateEvent(event(1)).event,corrupt={...event(2),filename:'private.xlsx'},store=memory(JSON.stringify({contractVersion:api.VERSION,events:[corrupt,valid,{rawWorkbook:'secret'}]})),history=api.create({storage:store}).history;const listed=history.list(scopeKey,20);assert.equal(listed.ok,true);assert.deepEqual(listed.events,[valid]);assert.doesNotMatch(JSON.stringify(listed),/private|secret/i);const broken=api.create({storage:memory('{broken')}).history;assert.deepEqual(broken.listAll(10),{ok:true,events:[]});});
test('source contains no raw-data or filename schema surface',()=>{const source=fs.readFileSync(new URL('../www/etp-import-history.js',import.meta.url),'utf8');assert.doesNotMatch(source,/\b(?:filename|fileLabel|filePath|workbookBytes|sourceRows|rawRows|customerName|mobileNumber)\b/);assert.doesNotMatch(source,/\b(?:const|let)\b|=>|\.padStart\(|\.padEnd\(/);});
