import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),api=require('../www/etp-tender-dictionary.js');
function dictionary(versionId='tender:v1',override={}){return{contractVersion:api.VERSION,versionId,effectiveAt:'2026-08-24T00:00:00Z',mappings:[{sourceField:'cash_amount',canonicalTender:'Cash'},{sourceField:'card_amount',canonicalTender:'Card'},{sourceField:'others_amount',canonicalTender:'Others'}],...override};}
function memory(initial=null){let value=initial,writes=0;return{getItem:key=>key===api.KEY?value:null,setItem(_key,next){writes++;value=next;},value:()=>value,writes:()=>writes};}
test('validates and deeply freezes an explicit versioned dictionary',()=>{const checked=api.validate(dictionary());assert.equal(checked.ok,true);assert.equal(Object.isFrozen(checked.dictionary),true);assert.equal(Object.isFrozen(checked.dictionary.mappings),true);assert.deepEqual(checked.dictionary.mappings.map(x=>x.sourceField),['card_amount','cash_amount','others_amount']);});
test('explicit mappings resolve, unknown sources remain Unmapped and never fold to Others',()=>{const value=dictionary();assert.deepEqual(api.resolve(value,'cash_amount'),{ok:true,classification:'Cash',mapped:true,persisted:true,dictionaryVersion:'tender:v1'});assert.deepEqual(api.resolve(value,'mystery_amount'),{ok:true,classification:'Unmapped',mapped:false,persisted:true,dictionaryVersion:'tender:v1'});assert.equal(api.resolve(value,'payment_type24_amount').classification,'Unmapped');assert.notEqual(api.resolve(value,'mystery_amount').classification,'Others');});
test('PAYMENTTYPE25 is permanently quarantined and cannot be overridden',()=>{const value=dictionary();assert.deepEqual(api.resolve(value,'payment_type25_amount'),{ok:true,classification:'Quarantined',mapped:false,persisted:false,dictionaryVersion:'tender:v1'});for(const canonicalTender of api.CANONICAL){const hostile=dictionary('hostile',{mappings:[{sourceField:'payment_type25_amount',canonicalTender}]});assert.equal(api.validate(hostile).code,'ETP_PAYMENTTYPE25_QUARANTINED');}});
test('Others is available only for the explicit others source',()=>{assert.equal(api.validate(dictionary('bad',{mappings:[{sourceField:'cash_amount',canonicalTender:'Others'}]})).code,'ETP_TENDER_MAPPING_INVALID');assert.equal(api.validate(dictionary('good',{mappings:[{sourceField:'others_amount',canonicalTender:'Others'}]})).ok,true);});
test('unknown fields, duplicate mappings, unsafe versions, extras and hostile prototypes fail closed',()=>{const cases=[dictionary('x',{mappings:[{sourceField:'customer_name',canonicalTender:'Cash'}]}),dictionary('x',{mappings:[{sourceField:'cash_amount',canonicalTender:'Cash'},{sourceField:'cash_amount',canonicalTender:'Card'}]}),dictionary('../bad'),{...dictionary(),filename:'private.xlsx'},Object.assign(Object.create({polluted:true}),dictionary())];for(const value of cases)assert.equal(api.validate(value).ok,false);});
test('registry preserves historical versions and refuses same-ID mutation',()=>{const store=memory(),registry=api.createRegistry({storage:store}).registry,first=dictionary();assert.equal(registry.register(first).changed,true);assert.equal(registry.register(first).changed,false);const changed=dictionary('tender:v1',{mappings:[{sourceField:'cash_amount',canonicalTender:'Card'}]});assert.equal(registry.register(changed).code,'ETP_TENDER_VERSION_IMMUTABLE');assert.equal(registry.get('tender:v1').dictionary.mappings.find(x=>x.sourceField==='cash_amount').canonicalTender,'Cash');assert.equal(store.writes(),1);});
test('corrupt stored versions are ignored without mutating valid immutable versions',()=>{const valid=api.validate(dictionary()).dictionary,store=memory(JSON.stringify({contractVersion:api.VERSION,versions:[{...dictionary('bad'),filename:'secret.xlsx'},valid]})),registry=api.createRegistry({storage:store}).registry;assert.deepEqual(registry.list().versions,[{versionId:'tender:v1',effectiveAt:'2026-08-24T00:00:00.000Z'}]);assert.equal(registry.get('tender:v1').ok,true);assert.equal(store.writes(),0);});
test('classic source has no crypto fiction or modern API dependency',()=>{const source=fs.readFileSync(new URL('../www/etp-tender-dictionary.js',import.meta.url),'utf8');assert.doesNotMatch(source,/\b(?:const|let)\b|=>|\.padStart\(|\.padEnd\(|btoa|atob|crypto\./);});
test('build dictionary has one immutable explicit identity and preserves quarantine semantics',()=>{assert.equal(Object.isFrozen(api.BUILD_DICTIONARY),true);assert.equal(Object.isFrozen(api.BUILD_IDENTITY),true);assert.deepEqual(api.BUILD_IDENTITY,{contractVersion:api.VERSION,versionId:'retail-etp-tender-v1',effectiveAt:'2026-08-24T00:00:00.000Z'});assert.equal(api.resolve(api.BUILD_DICTIONARY,'mystery_amount').classification,'Unmapped');assert.deepEqual(api.resolve(api.BUILD_DICTIONARY,'payment_type25_amount'),{ok:true,classification:'Quarantined',mapped:false,persisted:false,dictionaryVersion:'retail-etp-tender-v1'});assert.equal(api.resolve(api.BUILD_DICTIONARY,'payment_type24_amount').classification,'Unmapped');});
