import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url),api=require('../www/etp-verified-presentation.js');
const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30',scopeKey:'WLMHW|2026-27|2026-04-01..2026-04-30'},generation='etp_'+'a'.repeat(32);
function row(id){const value={};api.REPORT_FIELDS[id].forEach(field=>{value[field]=field==='transaction_type_raw'?'INV':field==='invoice_number'?'I-1':field==='brand'?'Titan':field==='cluster'?'Watches':field==='gender'?'Unisex':field==='cro_number'?'CRO-1':1;});return value;}
function response(id,change={}){const coverage=Object.fromEntries(api.REPORTS.map(reportId=>[reportId,{status:'COMPLETE',zeroActivityConfirmed:false}])),selected={...scope};return{ok:true,scope:selected,status:{ok:true,contractVersion:'ETP_FOUNDATION_V1',status:'READY_WITH_WARNINGS',showValues:true,reasons:[],warnings:['PAYMENTTYPE25_QUARANTINED'],scope:{...selected},activeGenerationId:generation,verifiedThrough:selected.periodEnd,publishedAt:'2026-05-01T00:00:00Z'},receipt:{contractVersion:'ETP_CORE_V1',scopeKey:selected.scopeKey,storeCode:'WLMHW',activeGenerationId:generation,profileVersion:'profile_v1',parserVersion:'parser_v1',profileAuthority:{contractVersion:'AUTH_V1',authorityId:'retail',storeCode:'WLMHW',status:'AUTHORIZED',purpose:'PRODUCTION',profileVersion:'profile_v1',parserVersion:'parser_v1',evidenceIdentity:'evidence'},tenderDictionary:{contractVersion:'TENDER_V1',versionId:'v1',effectiveAt:'2026-04-01'},ruleVersion:'rec_002_v1',reconciliationStatus:'PASS',publishedAt:'2026-05-01',coverage,exceptions:{R003:{status:'PASS',differenceCount:0},R013:{status:'PASS',differenceCount:0},paymentType25:{status:'QUARANTINED',rowCount:3,persisted:false}}},query:{reportId:id,fields:api.REPORT_FIELDS[id],filters:[],sort:[],limit:api.REPORT_LIMIT},page:{scopeKey:selected.scopeKey,generationId:generation,reportId:id,rows:[row(id)],scannedRows:1,filterOrderScope:'SOURCE_PAGE_ONLY',totals:'NOT_PROVIDED',hasMore:false,nextCursor:null},...change};}
test('iframe presentation consumes mocked query pages only and never requests native/raw access',async()=>{let received;const facade={async queryReport(selected,request){received={selected,request};return response('R013');},loadSummary(){throw Error('legacy browsing forbidden');},readFacts(){throw Error('raw forbidden');}};const result=await api.loadReport(facade,scope,'R013',[],null);assert.equal(result.ok,true);assert.equal(result.model.reportId,'R013');assert.equal(received.request.limit,api.REPORT_LIMIT);assert.deepEqual(received.request.fields,api.REPORT_FIELDS.R013);});
test('R003 and R013 are explicitly non-revenue views and no cross-report revenue aggregate exists',()=>{const source=fs.readFileSync(new URL('../www/etp-verified-presentation.js',import.meta.url),'utf8');assert.match(source,/R013:'CRO attribution \(non-revenue\)'/);assert.match(source,/R003:'Discounts \(non-revenue\)'/);const bounded=source.slice(source.indexOf('function renderReport'),source.indexOf('function renderWarnings'));assert.doesNotMatch(bounded,/total revenue|revenueUnits|summaryAdd/i);});
test('presentation rejects scope, generation, REC-002 and row-shape substitution',async()=>{for(const value of [response('R025',{page:{...response('R025').page,scopeKey:'HEMW|2026-27|2026-04-01..2026-04-30'}}),response('R025',{page:{...response('R025').page,generationId:'etp_'+'b'.repeat(32)}}),response('R025',{receipt:{...response('R025').receipt,reconciliationStatus:'FAIL'}}),response('R025',{page:{...response('R025').page,rows:[{...row('R025'),customer_name:'Secret'}]}})]){const result=await api.loadReport({queryReport:async()=>value},scope,'R025',[],null);assert.equal(result.code,'ETP_VIEW_REPORT_INVALID');}});
test('metadata projection rejects raw/native and PII-shaped nested additions',async()=>{for(const mutate of [value=>{value.scope.customer='Secret';},value=>{value.status.nativeStore={};},value=>{value.receipt.workbook='private.xlsx';},value=>{value.receipt.coverage.R022.rows=[];},value=>{value.query.rawCursor={chunkIndex:9};}]){const value=response('R022');mutate(value);const result=await api.loadReport({queryReport:async()=>value},scope,'R022',[],null);assert.equal(result.code,'ETP_VIEW_REPORT_INVALID');}});
test('a coherent alternate scope is rejected against the exact requested scope',async()=>{const value=response('R022'),alternate={storeCode:'HEMW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30',scopeKey:'HEMW|2026-27|2026-04-01..2026-04-30'};value.scope=alternate;value.status.scope=alternate;value.receipt.scopeKey=alternate.scopeKey;value.receipt.storeCode='HEMW';value.receipt.profileAuthority.storeCode='HEMW';value.page.scopeKey=alternate.scopeKey;assert.equal((await api.loadReport({queryReport:async()=>value},scope,'R022',[],null)).code,'ETP_VIEW_REPORT_INVALID');});
test('report contract declares page-local filtering/order and explicitly provides no totals',async()=>{const result=await api.loadReport({queryReport:async()=>response('R025')},scope,'R025',[],null);assert.equal(result.ok,true);const source=fs.readFileSync(new URL('../www/etp-verified-presentation.js',import.meta.url),'utf8');assert.match(source,/filter\/order is page-local · no totals/);assert.doesNotMatch(source.slice(source.indexOf('function renderReport'),source.indexOf('function renderWarnings')),/global total|grand total/i);});
test('PAYMENTTYPE25 is warning metadata; token-boundary PII checks retain legitimate PhonePe tender',()=>{const fields=Object.values(api.REPORT_FIELDS).flat();assert.equal(fields.includes('payment_type25_amount'),false);assert.equal(fields.includes('phonepe_amount'),true);for(const forbidden of ['customer','mobile','phone','email','address'])assert.equal(fields.includes(forbidden),false);});
