import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';

const require=createRequire(import.meta.url);
const api=require('../www/etp-module-gateway.js');
const query=require('../www/etp-query-contract.js');
const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-04-30'};
const scopeKey='WLMHW|2026-27|2026-04-01..2026-04-30',generation='etp_'+'a'.repeat(32);

function receipt(reconciliationStatus='PASS') { return {contractVersion:'ETP_CORE_V1',scopeKey,storeCode:'WLMHW',activeGenerationId:generation,profileVersion:'profile_v1',parserVersion:'parser_v1',profileAuthority:{contractVersion:'AUTH_V1',authorityId:'retail',storeCode:'WLMHW',status:'AUTHORIZED',purpose:'PRODUCTION',profileVersion:'profile_v1',parserVersion:'parser_v1',evidenceIdentity:'evidence'},tenderDictionary:{contractVersion:'TENDER_V1',versionId:'v1',effectiveAt:'2026-04-01'},ruleVersion:'rec_002_v1',reconciliationStatus,publishedAt:'2026-05-01',coverage:Object.fromEntries(['R003','R013','R022','R025'].map(id=>[id,{status:'COMPLETE',zeroActivityConfirmed:false}])),enrichments:{R003:{status:'PASS',differenceCount:0},R013:{status:'PASS',differenceCount:0},paymentType25:{status:'QUARANTINED',rowCount:2,persisted:false}},lifecycle:{scope}}; }
function fixture({reconciliationStatus='PASS',runtime}={}) {
  const current=receipt(reconciliationStatus),stored=JSON.stringify({scopes:{[scopeKey]:{current,history:[]}}});
  let writes=0,calls=[];
  const defaultRuntime={async run(){throw Error('write');},async confirm(){throw Error('write');},async readVerified(_scope,request){calls.push(request);return{ok:true,page:{scopeKey,generationId:generation,reportId:request.reportId,rows:[{invoice_number:'B2',net_amount:20,brand:'Titan'},{invoice_number:'A1',net_amount:10,brand:'Other'}],hasMore:true,nextCursor:{chunkIndex:1,rowOffset:0}}};}};
  const made=api.create({runtime:runtime||defaultRuntime,lifecyclePolicy:{validateScope(value){return value&&value.storeCode==='WLMHW'?{ok:true,key:scopeKey,scope}: {ok:false};}},core:{REPORTS:['R003','R013','R022','R025'],validateReceipt(value){return value&&value.activeGenerationId?{ok:true,receipt:value}:{ok:false};}},foundationStatus:{VERSION:'FOUNDATION_V1',evaluate({receipt:value}){const ready=value.reconciliationStatus==='PASS';return{ok:true,contractVersion:'FOUNDATION_V1',status:ready?'READY':'NOT_READY',showValues:ready,reasons:ready?[]:['REC_002_NOT_PASSED'],warnings:[],scope:{...scope,scopeKey},activeGenerationId:ready?generation:null,verifiedThrough:ready?scope.periodEnd:null,publishedAt:ready?'2026-05-01T00:00:00Z':null};}},queryContract:query,profileAuthority:{authorize(){return{ok:true};}},importHistoryApi:{create(){return{ok:true,history:{list(){return{ok:true,events:[]};}}};}},tenderDictionaryApi:{BUILD_DICTIONARY:{},validate(){return{ok:true};}},storage:{getItem(key){return key===api.REGISTRY_KEY?stored:null;},setItem(){writes++;}},statusReader:async()=>({ok:true,status:{state:'ACCEPTED',activeGenerationId:generation,restoreFence:false}}),authorize:action=>action==='READ',tokenFactory:()=> 'c'.repeat(32)});
  return{...made,calls,writes:()=>writes};
}
function request(overrides={}) { return{contractVersion:query.VERSION,reportId:'R025',fields:['invoice_number','net_amount','brand'],filters:[{field:'brand',operator:'EQ',value:'Titan'}],sort:[{field:'net_amount',direction:'DESC'}],limit:50,cursor:null,...overrides}; }

test('parent query performs one bounded page-local filter/order read without totals or writes',async()=>{const fx=fixture(),result=await fx.gateway.readFacade.queryReport(scope,request());assert.equal(result.ok,true);assert.deepEqual(result.page.rows,[{invoice_number:'B2',net_amount:20,brand:'Titan'}]);assert.equal(result.page.scannedRows,2);assert.equal(result.page.filterOrderScope,'SOURCE_PAGE_ONLY');assert.equal(result.page.totals,'NOT_PROVIDED');assert.match(result.page.nextCursor,/^cur_/);assert.equal(fx.calls.length,1);assert.equal(fx.calls[0].limit,50);assert.equal(fx.writes(),0);assert.equal(Object.isFrozen(result.page.rows),true);});
test('native compact invoice dates cross the gateway only as canonical ISO dates',async()=>{const runtime={async run(){throw Error('write');},async confirm(){throw Error('write');},async readVerified(_scope,value){return{ok:true,page:{scopeKey,generationId:generation,reportId:value.reportId,rows:[{invoice_date:'20260409',invoice_number:'A1'}],hasMore:false,nextCursor:null}};}};const fx=fixture({runtime});const result=await fx.gateway.readFacade.queryReport(scope,{contractVersion:query.VERSION,reportId:'R022',fields:['invoice_date','invoice_number'],filters:[],sort:[{field:'invoice_date',direction:'ASC'}],limit:50,cursor:null});assert.equal(result.ok,true,JSON.stringify(result));assert.deepEqual(result.page.rows,[{invoice_date:'2026-04-09',invoice_number:'A1'}]);});
test('opaque paging is isolated by filter, scope and generation binding',async()=>{const fx=fixture(),first=await fx.gateway.readFacade.queryReport(scope,request()),before=fx.calls.length;assert.equal((await fx.gateway.readFacade.queryReport(scope,request({filters:[{field:'brand',operator:'EQ',value:'Other'}],cursor:first.page.nextCursor}))).code,'ETP_REPORT_CURSOR_INVALID');assert.equal((await fx.gateway.readFacade.queryReport({...scope,storeCode:'HEMW'},request({cursor:first.page.nextCursor}))).code,'ETP_SCOPE_INVALID');assert.equal(fx.calls.length,before);});
test('REC-002 incomplete status suppresses all rows before fact access',async()=>{const fx=fixture({reconciliationStatus:'FAIL'}),result=await fx.gateway.readFacade.queryReport(scope,request());assert.equal(result.code,'ETP_REPORT_NOT_READY');assert.equal(fx.calls.length,0);assert.doesNotMatch(JSON.stringify(result),/rows|total/i);});
test('bounded release source exposes no export or native/raw iframe capability',()=>{const source=fs.readFileSync(new URL('../www/etp-module-gateway.js',import.meta.url),'utf8');assert.doesNotMatch(source,/queryReport[\s\S]{0,5000}(?:export|download|csv|xlsx)/i);assert.match(source,/One native page in, one sanitized report page out/);assert.doesNotMatch(source,/readFacade\s*=\s*[^;]*(?:nativeStore|plugin|readFacts)/);});
