import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url), api = require('../www/etp-verified-analytics.js');
const scope = Object.freeze({storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-04-01',periodEnd:'2026-08-24',scopeKey:'WLMHW|2026-27|2026-04-01..2026-08-24'});
const receipt = Object.freeze({reconciliationStatus:'PASS',ruleVersion:'rec_002_v1',coverage:Object.fromEntries(api.REPORTS.map(id=>[id,{status:'COMPLETE'}])),exceptions:{paymentType25:{status:'QUARANTINED',rowCount:7,persisted:false}}});
function row(date, extra={}) { return {invoice_date:date,store_code:'WLMHW',transaction_type_raw:'INV',...extra}; }
const rows = Object.freeze({
  R022:[row('2026-08-24',{invoice_number:'1',net_value:'100.00',cash_amount:'40',card_amount:'60'}),row('2026-08-24',{invoice_number:'2',net_value:'50.00',cash_amount:'50'}),row('2026-08-23',{invoice_number:'3',net_value:'25.00',cash_amount:'25'})],
  R025:[row('2026-08-24',{invoice_number:'1',quantity:'2',net_amount:'100',brand:'Titan'}),row('2026-08-24',{invoice_number:'2',quantity:'1',net_amount:'50',brand:'Fastrack'}),row('2026-08-24',{invoice_number:'4',transaction_type_raw:'SR',quantity:'-1',net_amount:'-10',brand:'Titan'}),row('2026-08-23',{invoice_number:'3',quantity:'1',net_amount:'25',brand:'Titan'})],
  R013:[row('2026-08-24',{cro_number:'CRO-1',net_amount:'120',quantity:'2'}),row('2026-08-23',{cro_number:'CRO-2',net_amount:'25',quantity:'1'})],
  R003:[row('2026-08-24',{net_amount:'150',scheme_discount:'3',user_discount:'5'}),row('2026-08-23',{net_amount:'25',scheme_discount:'0',user_discount:'1'})]
});
function request(changes={}) { return {scope,status:{verifiedThrough:'2026-08-24'},receipt,asOfDate:'2026-08-24',view:'DAY',rows,...changes}; }
test('DAY computes verified metrics/mixes/exceptions and permanent store-net identity',()=>{const out=api.build(request());assert.equal(out.ok,true);assert.deepEqual(out.analytics.metrics,{netSale:15000,bills:2,units:2000,atv:7500,upt:1000,asp:7500});assert.deepEqual(out.analytics.identity,{storeNet:15000,croAchievement:12000,unassigned:3000,reconciles:true});assert.equal(out.analytics.exceptions.returns,-1000);assert.equal(out.analytics.exceptions.returnsBps,625);assert.equal(out.analytics.exceptions.manualDiscount,500);assert.equal(out.analytics.exceptions.paymentType25,7);assert.ok(out.analytics.mixes.tender.every(x=>x.label!=='PAYMENTTYPE25'));assert.equal(Object.isFrozen(out.analytics),true);});
test('MTD/YTD declare exact period-end semantics and partial labels',()=>{const mtd=api.build(request({view:'MTD',asOfDate:'2026-08-24'})).analytics;assert.equal(mtd.period.start,'2026-08-01');assert.equal(mtd.period.end,'2026-08-24');assert.equal(mtd.period.partial,false);const partial=api.build(request({view:'YTD',scope:{...scope,periodStart:'2026-05-01',scopeKey:'WLMHW|2026-27|2026-05-01..2026-08-24'}})).analytics;assert.equal(partial.coverage.complete,false);assert.equal(partial.metrics.netSale,null);assert.match(partial.coverage.label,/—/);});
test('honest missing coverage renders null values instead of zeros',()=>{const out=api.build(request({receipt:{...receipt,coverage:{...receipt.coverage,R025:{status:'MISSING'}}}})).analytics;assert.equal(out.coverage.complete,false);assert.equal(out.metrics.units,null);assert.equal(out.metrics.netSale,null);assert.deepEqual(out.coverage.missingReports,['R025']);});
test('LY requires an isolated same-store comparison scope and never borrows another store',()=>{const lyScope={storeCode:'WLMHW',financialYear:'2025-26',periodStart:'2025-04-01',periodEnd:'2025-08-24',scopeKey:'WLMHW|2025-26|2025-04-01..2025-08-24'};const missing=api.build(request({view:'LY'})).analytics;assert.equal(missing.coverage.complete,false);const crossed=api.build(request({view:'LY',comparisonScope:{...lyScope,storeCode:'HEMW',scopeKey:'HEMW|2025-26|2025-04-01..2025-08-24'},comparisonRows:rows})).analytics;assert.equal(crossed.coverage.complete,false);});
test('REC-002/readiness, store row isolation and R003/R013 non-revenue fail closed',()=>{assert.equal(api.build(request({receipt:{...receipt,reconciliationStatus:'FAIL'}})).code,'ETP_ANALYTICS_NOT_READY');const poisoned={...rows,R022:[{...rows.R022[0],store_code:'HEMW'}]};assert.equal(api.build(request({rows:poisoned})).code,'ETP_ANALYTICS_FACTS_INVALID');const changed={...rows,R003:[row('2026-08-24',{net_amount:'999999',user_discount:'5'})],R013:[row('2026-08-24',{cro_number:'CRO-1',net_amount:'120'})]};assert.equal(api.build(request({rows:changed})).analytics.metrics.netSale,15000);});
test('domain source has no native/raw gateway or persistence authority',()=>{const source=fs.readFileSync(new URL('../www/etp-verified-analytics.js',import.meta.url),'utf8');assert.doesNotMatch(source,/Capacitor|SaagarEtpNativeStore|readFacts|indexedDB|localStorage|sessionStorage|innerHTML|window\.parent|postMessage/);assert.doesNotMatch(source,/payment_type25_amount/);});
