import assert from 'node:assert/strict';
import test from 'node:test';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const api=require('../www/etp-cro-reconciliation.js');
const act=(role='manager',at='2026-08-24T10:00:00.000Z',reason='reviewed correction')=>({actor:'tester',role,at,reason});
const scope={storeId:'WLMHW',businessDate:'2026-08-24'};
const verified=rows=>({source:'ETP_VERIFIED',scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31',generationId:'etp_'+'a'.repeat(32),receiptId:'receipt-verified-1',rows});
function ok(result){assert.equal(result.ok,true,result.code);return result.day;}
function seeded(){let d=ok(api.createDay(scope));d=ok(api.declare(d,{invoiceId:'I1',croId:'C1',netAmount:100},act('staff')));d=ok(api.declare(d,{invoiceId:'I3',croId:'C3',netAmount:25},act('staff')));d=ok(api.declare(d,{invoiceId:'P1',croId:'C9',netAmount:9},act('staff')));d=ok(api.transition(d,'CLOSED',act()));d=ok(api.importFacts(d,verified([{invoiceId:'I1',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:100,croId:'C2'},{invoiceId:'I2',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:50,croId:null},{invoiceId:'I3',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:25,croId:'C3'}]),act()));d=ok(api.transition(d,'IMPORTED',act()));return d;}
test('contract is deeply immutable and declares invoice-grain records only',()=>{assert.ok(Object.isFrozen(api));assert.ok(Object.isFrozen(api.STATES));let d=ok(api.createDay(scope));assert.equal(api.declare(d,{croId:'C1',netAmount:1},act()).code,'DECLARATION_INVALID');d=ok(api.declare(d,{invoiceId:'I1',croId:'C1',netAmount:10},act('staff')));assert.equal(d.declarations.length,1);assert.equal(api.declare(d,{invoiceId:'I1',croId:'C2',netAmount:10},act()).code,'INVOICE_DUPLICATE');});
test('state graph is exact and fail closed',()=>{let d=ok(api.createDay(scope));assert.equal(api.transition(d,'IMPORTED',act()).code,'TRANSITION_INVALID');d=ok(api.transition(d,'CLOSED',act()));assert.equal(api.transition(d,'IMPORTED',act()).code,'SOURCE_FACTS_REQUIRED');assert.deepEqual(api.STATES,['OPEN','CLOSED','IMPORTED','RECONCILED','VARIANCE','LOCKED']);});
test('matcher produces all four outcomes and an unassigned queue',()=>{let d=seeded();const r=api.reconcile(d,act());d=ok(r);assert.equal(r.suggestedState,'VARIANCE');assert.deepEqual(d.outcomes.map(x=>x.outcome).sort(),['Matched','Misattributed','Phantom','Unclaimed']);assert.deepEqual(d.unassignedQueue,['I2']);assert.equal(api.transition(d,'RECONCILED',act()).code,'VARIANCE_REMAINS');});
test('store net excludes declarations and reconciles only verified facts',()=>{let d=ok(api.createDay(scope));for(const row of [{invoiceId:'I1',croId:'C1',netAmount:100},{invoiceId:'I2',croId:'C2',netAmount:50}])d=ok(api.declare(d,row,act('staff')));assert.equal(api.totals(d).storeNet,null);d=ok(api.transition(d,'CLOSED',act()));d=ok(api.importFacts(d,verified([{invoiceId:'I1',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:90,croId:'C1'},{invoiceId:'I2',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:60,croId:null}]),act()));d=ok(api.transition(d,'IMPORTED',act()));const t=api.totals(d);assert.equal(t.source,'ETP_VERIFIED');assert.equal(t.storeNet,t.assignedNet+t.unassigned);});
test('24-hour freeze requires owner and every correction audits complete before/after metadata',()=>{let d=seeded();assert.equal(api.correctAttribution(d,{invoiceId:'I2',croId:'C3'},act('staff','2026-08-24T11:00:00Z','claim receipt')).code,'E3_ROLE_DENIED');d=ok(api.correctAttribution(d,{invoiceId:'I2',croId:'C3'},act('manager','2026-08-24T11:00:00Z','claim receipt')));assert.equal(api.correctAttribution(d,{invoiceId:'I1',croId:'C1'},act('manager','2026-08-26T11:00:00Z')).code,'OWNER_REQUIRED_AFTER_FREEZE');d=ok(api.correctAttribution(d,{invoiceId:'I1',croId:'C1'},act('owner','2026-08-26T11:00:00Z','owner correction')));const a=d.audit.at(-1);assert.deepEqual(a.before,{invoiceId:'I1',croId:'C2'});assert.equal(a.after.croId,'C1');assert.equal('sourceFacts' in a.before,false);assert.ok(Object.isFrozen(a));});

test('confirmed owner policy enforces declaration, close, correction, disposition and immutable-lock roles',()=>{assert.equal(api.POLICY_VERSION,'ETP_E3_OWNER_POLICY_2026_08_25_V1');assert.deepEqual(api.POLICY.declarationRoles,['Staff','Store Manager','Owner']);assert.equal(api.POLICY.correctionWindowHours,24);let d=ok(api.createDay(scope));d=ok(api.declare(d,{invoiceId:'I1',croId:'C1',netAmount:10},act('owner')));assert.equal(api.transition(d,'CLOSED',act('staff')).code,'E3_ROLE_DENIED');d=ok(api.transition(d,'CLOSED',act('owner')));assert.equal(api.importFacts(d,verified([{invoiceId:'I1',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:10,croId:'C1'}]),act('staff')).code,'IMPORT_INVALID');});
test('variance needs manager disposition before lock and locked days reject mutation',()=>{let d=ok(api.reconcile(seeded(),act()));d=ok(api.transition(d,'VARIANCE',act()));assert.equal(api.disposeVariance(d,{code:'ACCEPTED_VARIANCE'},act('staff')).code,'MANAGER_DISPOSITION_INVALID');assert.equal(api.transition(d,'LOCKED',act()).code,'MANAGER_DISPOSITION_REQUIRED');d=ok(api.disposeVariance(d,{code:'SOURCE_REVIEWED',invoiceId:'I1'},act('manager')));d=ok(api.transition(d,'LOCKED',act()));assert.equal(api.correctAttribution(d,{invoiceId:'I1',croId:'C9'},act('owner')).code,'DAY_LOCKED');});
test('overlay serialization is durable, restorable and rejects malformed/tampered snapshots',()=>{const d=seeded();const s=api.serialize(d);assert.equal(s.ok,true);const restored=api.restore(s.overlay);assert.equal(restored.ok,true);assert.deepEqual(restored.day,d);const tampered=JSON.parse(s.overlay);tampered.day.sourceFacts[0].netAmount='not-money';assert.equal(api.restore(JSON.stringify(tampered)).code,'RESTORE_DAY_INVALID');const hostile=JSON.parse(s.overlay);hostile.day.assignments.constructor='C1';assert.equal(api.restore(JSON.stringify(hostile)).code,'RESTORE_DAY_INVALID');});
test('source facts require a verified binding and cross-store imports fail closed',()=>{let d=ok(api.createDay(scope));d=ok(api.transition(d,'CLOSED',act()));assert.equal(api.importFacts(d,{source:'ETP_VERIFIED',rows:[]},act()).code,'VERIFIED_SOURCE_BINDING_INVALID');const bad=api.importFacts(d,verified([{invoiceId:'X',storeId:'HEMW',invoiceDate:'2026-08-24',netAmount:1,croId:'C'}]),act());assert.equal(bad.code,'SOURCE_FACT_INVALID');assert.deepEqual(d.sourceFacts,[]);});
