import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import presentation from '../www/etp-e6-presentation.js';

class Node{constructor(doc,tag='div'){this.ownerDocument=doc;this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.disabled=false;this.className='';this.textContent='';}get firstChild(){return this.children[0]||null;}appendChild(v){this.children.push(v);return v;}removeChild(v){this.children.splice(this.children.indexOf(v),1);}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(k,v){this.listeners[k]=v;}}
const document={createElement:tag=>new Node(document,tag)};
const all=node=>[node,...node.children.flatMap(all)];
const text=node=>all(node).map(n=>n.textContent).filter(Boolean).join(' | ');
const host=()=>new Node(document);
const scope={scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31',storeCode:'WLMHW'};
const actor={actorId:'manager-1',role:'Store Manager'};
const hash='a'.repeat(64);
function item(){return{id:'DECLARED_ACTUAL_VARIANCE|WLMHW|CRO-1|2026-08-25|policy-v1',type:'DECLARED_ACTUAL_VARIANCE',scopeKey:scope.scopeKey,storeCode:'WLMHW',entityId:'CRO-1',ownerId:'manager-1',ownerRole:'Store Manager',defaultOwnerId:'manager-1',detectedAt:'2026-08-25',ageDays:3,slaDays:2,dueAt:'2026-08-27T00:00:00.000Z',slaStatus:'OVERDUE',status:'OPEN',generationId:'etp_'+'1'.repeat(32),receiptId:'receipt-1',evidence:{kind:'DECLARED_ACTUAL_BPS',reference:'evidence-1',observed:1500,threshold:1000},closureReason:null,closedAt:null,evidenceHistory:[{action:'EVIDENCE_ADDED',at:'2026-08-26T10:00:00.000Z',actorId:'manager-1',actorRole:'Store Manager',evidenceReference:'evidence-1'}],history:[{action:'OPENED',at:'2026-08-25T00:00:00.000Z',actorId:'SYSTEM',actorRole:'System',evidenceReference:'evidence-1'}]};}
function model(status='READY'){const ready=status==='READY';return{ok:true,status,authority:{status:ready?'APPROVED':'MISSING',approvalId:ready?'owner-approval-1':null,sourceSha256:ready?hash:null},thresholds:ready?{versionId:'e6-thresholds-v1'}:null,policy:{closureReasonCodes:ready?['CORRECTED_AND_VERIFIED','ACCEPTED_WITH_EVIDENCE']:[]},exceptions:ready?[item()]:[],summary:ready?{open:1,acknowledged:0,closed:0,overdue:1}:{open:0,acknowledged:0,closed:0,overdue:0},actions:{refresh:ready,acknowledge:ready,reassign:ready,addEvidence:ready,close:ready}};}

test('renders an honest blocked state without exception or action leakage',async()=>{const root=host(),mounted=presentation.mount(root,{load:async()=>model('BLOCKED')},{getScope:()=>scope,getActor:()=>actor});assert.equal((await mounted.refresh()).ok,true);const content=text(root);assert.match(content,/E6 exception monitoring blocked/);assert.match(content,/fail-closed/);assert.match(content,/Authority: MISSING/);assert.match(content,/No approved policy hash/);assert.doesNotMatch(content,/CRO-1|evidence-1/);for(const button of all(root).filter(n=>n.tagName==='BUTTON'))assert.equal(button.disabled,true);});

test('renders owner, SLA, age, verified evidence, state and append-only histories',async()=>{const root=host(),mounted=presentation.mount(root,{load:async()=>model()},{getScope:()=>scope,getActor:()=>actor});await mounted.refresh();const content=text(root);for(const phrase of ['Authority: APPROVED','Owner approval: owner-approval-1','Policy SHA-256','Threshold version: e6-thresholds-v1','DECLARED ACTUAL VARIANCE','Owner','manager-1 · Store Manager','Age','3 days','OVERDUE · 2 days','Due: 2026-08-27','Evidence','DECLARED_ACTUAL_BPS','Verified binding','receipt-1','History · 1 events','Evidence history · 1 entries'])assert.match(content,new RegExp(phrase));assert.equal(all(root).some(n=>'innerHTML'in n),false);});

test('routes governed actions through bounded scope/input and retries after denial',async()=>{const root=host(),calls=[];let deny=true,loads=0;const facade={load:async request=>{loads++;assert.deepEqual(request,{scope});return model();},refresh:async request=>{calls.push(['refresh',request]);return{ok:true};},acknowledge:async request=>{calls.push(['acknowledge',request]);if(deny){deny=false;return{ok:false,code:'E6_ACTION_REAUTH_REQUIRED'};}return{ok:true};},reassign:async request=>{calls.push(['reassign',request]);return{ok:true};},addEvidence:async request=>{calls.push(['addEvidence',request]);return{ok:true};},close:async request=>{calls.push(['close',request]);return{ok:true};}};const mounted=presentation.mount(root,facade,{getScope:()=>scope,getActor:()=>actor,getActionInput:(name,id)=>Object.freeze({operation:name,exceptionId:id,evidenceReference:'evidence-2',closureReason:'VERIFIED_RESOLVED'})});await mounted.refresh();assert.equal((await mounted.acknowledge(item().id)).code,'E6_ACTION_REAUTH_REQUIRED');assert.match(text(root),/E6_ACTION_REAUTH_REQUIRED/);assert.equal(all(root).filter(n=>n.tagName==='BUTTON').every(n=>!n.disabled),true);assert.equal((await mounted.acknowledge(item().id)).ok,true);assert.equal((await mounted.reassign(item().id)).ok,true);assert.equal((await mounted.addEvidence(item().id)).ok,true);assert.equal((await mounted.close(item().id)).ok,true);assert.equal((await mounted.runRefresh()).ok,true);assert.equal(loads,6);assert.deepEqual(calls.map(x=>x[0]),['acknowledge','acknowledge','reassign','addEvidence','close','refresh']);for(const [,request]of calls){assert.deepEqual(request.scope,scope);assert.equal('actor'in request,false);assert.equal(request.input.operation.length>0,true);}});

test('fails closed on scope or actor drift before calling a mutation',async()=>{const root=host();let liveScope=scope,liveActor=actor,calls=0;const facade={load:async()=>model(),acknowledge:async()=>{calls++;return{ok:true};}};const mounted=presentation.mount(root,facade,{getScope:()=>liveScope,getActor:()=>liveActor});await mounted.refresh();liveActor={actorId:'owner-2',role:'Owner'};assert.equal((await mounted.acknowledge(item().id)).code,'E6_PRESENTATION_CONTEXT_CHANGED');assert.equal(calls,0);assert.match(text(root),/E6_PRESENTATION_CONTEXT_CHANGED/);liveActor=actor;await mounted.refresh();liveScope={...scope,scopeKey:'WLMHW|2026-27|2026-09-01..2026-09-30'};assert.equal((await mounted.acknowledge(item().id)).code,'E6_PRESENTATION_CONTEXT_CHANGED');assert.equal(calls,0);});

test('requires manager authority and sanitizes backend failures',async()=>{const root=host();let calls=0;const facade={load:async()=>model(),acknowledge:async()=>{calls++;return{ok:false,code:'private/path'};}};const staff=presentation.mount(root,facade,{getScope:()=>scope,getActor:()=>({actorId:'staff-1',role:'Staff'})});await staff.refresh();assert.equal((await staff.acknowledge(item().id)).code,'E6_PRESENTATION_ACTION_UNAVAILABLE');assert.equal(calls,0);const manager=presentation.mount(root,facade,{getScope:()=>scope,getActor:()=>actor});await manager.refresh();assert.equal((await manager.acknowledge(item().id)).code,'E6_PRESENTATION_ACTION_FAILED');assert.doesNotMatch(text(root),/private\/path/);});

test('rejects READY authority without Owner approval/hash/threshold/reason codes and BLOCKED leakage',()=>{for(const mutate of [v=>{v.authority.approvalId=null;},v=>{v.authority.sourceSha256='bad';},v=>{v.thresholds=null;},v=>{v.policy.closureReasonCodes=[];}]){const value=model();mutate(value);assert.equal(presentation.cleanModel(value),null);}const blocked=model('BLOCKED');blocked.exceptions=[item()];assert.equal(presentation.cleanModel(blocked),null);});

test('source is capability-bounded and CSS is mobile-safe without horizontal sliding',()=>{const source=fs.readFileSync(new URL('../www/etp-e6-presentation.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../www/etp-e6-presentation.css',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB|Capacitor|SaagarNative|window\.parent|parent\.postMessage|document\.(?:querySelector|getElementById)|innerHTML|fetch\s*\(|XMLHttpRequest/);assert.match(source,/host\.ownerDocument/);assert.match(source,/textContent/);assert.match(css,/min-height:44px/);assert.match(css,/max-width:100%/);assert.match(css,/minmax\(min\(100%,150px\),1fr\)/);assert.match(css,/@media\(max-width:480px\)/);assert.match(css,/@media\(min-width:900px\)/);assert.doesNotMatch(css,/100vw|overflow-x:\s*auto/);});
