import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url),api=require('../www/etp-operational-runtime.js'),storeApi=require('../www/etp-operational-store.js'),foundation=require('../www/etp-operational-foundation.js'),adapters=require('../www/etp-operational-adapters.js');
const scope='WLMHW|2026-27|2026-08-01..2026-08-31',item=(id='day-1')=>({domain:'E3',storeCode:'WLMHW',financialYear:'2026-27',scopeKey:scope,overlayId:id,updatedAt:'2026-08-25T09:00:00.000Z',payload:{state:'VARIANCE'}});
function memory(seed){let map=new Map(Object.entries(seed||{})),failSet=false,crashCurrent=false;return{getItem:k=>map.has(k)?map.get(k):null,setItem(k,v){if(failSet)throw Error('write');if(crashCurrent&&k==='saagar_etp_operational_v1')throw Error('crash');map.set(k,String(v));},removeItem:k=>map.delete(k),map,set fail(v){failSet=v;},set crash(v){crashCurrent=v;}};}
function made(storage){let out=api.create({storage,storeApi,foundation});assert.equal(out.ok,true,out.code);return out.runtime;}
test('persists deterministic repository mutations and reloads after restart',()=>{let storage=memory(),runtime=made(storage),repo=runtime.repository;assert.equal(repo.put(item(),0).ok,true);let saved=storage.map.get(api.DEFAULT_KEY);assert.ok(saved);let restarted=made(storage);assert.equal(restarted.repository.get({domain:'E3',storeCode:'WLMHW',financialYear:'2026-27',scopeKey:scope,overlayId:'day-1'}).found,true);assert.equal(storage.map.get(api.DEFAULT_KEY),saved);assert.equal('serialize'in restarted.repository,false);});
test('failed write rolls in-memory mutation back and preserves prior current value',()=>{let storage=memory(),runtime=made(storage),repo=runtime.repository;repo.put(item(),0);let prior=storage.map.get(api.DEFAULT_KEY);storage.fail=true;assert.equal(repo.put({...item(),updatedAt:'2026-08-25T10:00:00.000Z',payload:{state:'LOCKED'}},1).code,'ETP_RUNTIME_WRITE_FAILED');storage.fail=false;assert.equal(storage.map.get(api.DEFAULT_KEY),prior);assert.equal(repo.get({domain:'E3',storeCode:'WLMHW',financialYear:'2026-27',scopeKey:scope,overlayId:'day-1'}).revision,1);});
test('crash after staged temp recovers verified temp or rollback deterministically',()=>{let storage=memory(),runtime=made(storage);runtime.repository.put(item(),0);let old=storage.map.get(api.DEFAULT_KEY);storage.crash=true;assert.equal(runtime.repository.put({...item(),updatedAt:'2026-08-25T10:00:00.000Z'},1).code,'ETP_RUNTIME_WRITE_FAILED');storage.crash=false;assert.equal(made(storage).repository.get({domain:'E3',storeCode:'WLMHW',financialYear:'2026-27',scopeKey:scope,overlayId:'day-1'}).revision,1);assert.equal(storage.map.get(api.DEFAULT_KEY),old);});
test('bounded corrupt current fails closed unless a valid rollback exists',()=>{let storage=memory({'saagar_etp_operational_v1':'corrupt'});assert.equal(api.create({storage,storeApi,foundation}).code,'ETP_RUNTIME_CORRUPT');let clean=memory(),runtime=made(clean);runtime.repository.put(item(),0);let valid=clean.map.get(api.DEFAULT_KEY);clean.map.set(api.DEFAULT_KEY,'corrupt');clean.map.set(api.DEFAULT_KEY+'.rollback',valid);assert.equal(made(clean).repository.get({domain:'E3',storeCode:'WLMHW',financialYear:'2026-27',scopeKey:scope,overlayId:'day-1'}).found,true);});
test('portable import persists restore fence and exact rebind across restart',()=>{let sourceStorage=memory(),source=made(sourceStorage);source.repository.put(item(),0);let backup=source.exportPortable('2026-08-25T10:00:00.000Z').backup,targetStorage=memory(),target=made(targetStorage),binding={source:'ETP_VERIFIED',scopeKey:scope,generationId:'etp_'+'a'.repeat(32),receiptId:'receipt-1'};assert.equal(target.importPortable(backup,'2026-08-25T11:00:00.000Z').ok,true);assert.equal(target.canReadVerifiedScope(scope,binding),false);assert.equal(made(targetStorage).canReadVerifiedScope(scope,binding),false);assert.equal(target.rebindVerifiedScope(binding).ok,true);assert.equal(made(targetStorage).canReadVerifiedScope(scope,binding),true);assert.equal(made(targetStorage).canReadVerifiedScope(scope,{...binding,receiptId:'receipt-2'}),false);});
test('canonical repository rejects cross-store writes through runtime adapter surface',()=>{let repo=made(memory()).repository,bad={...item(),storeCode:'HEMW'};assert.equal(repo.put(bad,0).code,'ETP_STORE_OVERLAY_INVALID');assert.equal(repo.list({domain:'E3',storeCode:'HEMW',financialYear:'2026-27',scopeKey:scope}).code,'ETP_STORE_QUERY_INVALID');});
test('repository instance is directly compatible with canonical operational adapters',()=>{let storage=memory(),runtime=made(storage),madeAdapter=adapters.createE4({operationalStore:runtime.repository,scopeKey:scope,now:()=> '2026-08-25T10:00:00.000Z'}),binding={source:'ETP_VERIFIED',scopeKey:scope,generationId:'etp_'+'a'.repeat(32),receiptId:'receipt-1'};assert.equal(madeAdapter.ok,true);madeAdapter.adapter.saveSourceIntake(scope,{TITAN_TARGET:{sourceSha256:'a'.repeat(64)}},{kind:'SOURCE_INTAKE',inputIdentity:'x',value:{binding},operationId:'source-1'});assert.equal(made(storage).repository.list({domain:'E4',storeCode:'WLMHW',financialYear:'2026-27',scopeKey:scope}).items.length,2);});
test('source is injected, API23 safe and never exposes storage, native or raw facts',()=>{let source=fs.readFileSync(new URL('../www/etp-operational-runtime.js',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|document\.|window\.|fetch\s*\(|XMLHttpRequest|\?\.|\?\?|sourceFacts|rawRows|workbook/);});
