import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import presentation from '../www/etp-e7-presentation.js';

class Node{constructor(doc,tag='div'){this.ownerDocument=doc;this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.disabled=false;this.className='';this.textContent='';}get firstChild(){return this.children[0]||null;}appendChild(v){this.children.push(v);return v;}removeChild(v){this.children.splice(this.children.indexOf(v),1);}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(k,v){this.listeners[k]=v;}}
const document={createElement:tag=>new Node(document,tag)};
const all=node=>[node,...node.children.flatMap(all)];
const text=node=>all(node).map(n=>n.textContent).filter(Boolean).join(' | ');
const host=()=>new Node(document);
const scope={scopeKey:'SERVICE_ETP_V1|SC01|2026-27|2026-08-01..2026-08-31'};
const actor={actorId:'OWNER-1',role:'Owner'};
const binding={source:'ETP_VERIFIED',boundary:'SERVICE_ETP_V1',scopeKey:scope.scopeKey,generationId:'etp_'+'7'.repeat(32),receiptId:'service-receipt-001'};
const authorityIdentity={SERVICE_REPORT_IDENTITY_SET:{sourceSha256:'1'.repeat(64),approvalId:'OWNER-REPORTS-01'},SERVICE_PAYMENT_DICTIONARY:{sourceSha256:'2'.repeat(64),approvalId:'OWNER-PAY-01'}};
const evidence=[{kind:'SOURCE_PROJECTION',reference:'s003-row-001',generationId:binding.generationId,receiptId:binding.receiptId}];
function result(variance=true){return{ok:true,status:variance?'VARIANCE':'VERIFIED',boundary:'SERVICE_ETP_V1',scopeKey:scope.scopeKey,generationId:binding.generationId,receiptId:binding.receiptId,summary:{jobCount:2,matchedCount:1,discrepancyCount:variance?1:0},matches:[{jobKey:'JOB-001',revenuePaise:10000,tenderPaise:10000,variancePaise:0,evidence}],discrepancies:variance?[{discrepancyId:'verify-001|JOB-002|AMOUNT_VARIANCE',discrepancyType:'AMOUNT_VARIANCE',status:'OPEN',jobKey:'JOB-002',revenuePaise:25000,tenderPaise:24000,variancePaise:1000,evidence}]:[],snapshots:{}};}
function model(withState=true){const run={operationId:'verify-001',verifiedAt:'2026-08-25T10:00:00.000Z',binding,result:result()};return{ok:true,status:withState?'READY':'READY_FOR_VERIFICATION',boundary:'SERVICE_ETP_V1',scopeKey:scope.scopeKey,binding,authorityIdentity,state:withState?{contractVersion:'ETP_E7_SERVICE_OPERATIONAL_V1',scopeKey:scope.scopeKey,authorityIdentity,activeBinding:binding,runs:[run],evidence:[{eventId:'evidence-001',discrepancyId:run.result.discrepancies[0].discrepancyId,runOperationId:'verify-001',actorId:'OWNER-1',actorRole:'Owner',at:'2026-08-25T10:05:00.000Z',evidenceKind:'SOURCE_CHECK',evidenceReference:'service-proof-001',note:'Checked'}],closures:[],audit:[{sequence:1,event:'VERIFIED',referenceId:'verify-001',at:'2026-08-25T10:00:00.000Z'},{sequence:2,event:'EVIDENCE_ADDED',referenceId:'evidence-001',at:'2026-08-25T10:05:00.000Z'}],updatedAt:'2026-08-25T10:05:00.000Z'}:null};}

test('missing authority/source remains prominently BLOCKED and deferred without fabricated content',async()=>{const root=host(),mounted=presentation.mount(root,{load:()=>({ok:false,status:'BLOCKED',code:'E7_AUTHORITY_DEFERRED'})},{getScope:()=>scope,getActor:()=>null});const out=await mounted.refresh();assert.equal(out.code,'E7_AUTHORITY_DEFERRED');assert.match(text(root),/BLOCKED \/ deferred/);assert.match(text(root),/E7_AUTHORITY_DEFERRED/);assert.match(text(root),/Separate Owner-approved service authority/);assert.equal(all(root).some(n=>n.tagName==='BUTTON'),false);});

test('renders isolated SERVICE_ETP_V1 S003/S004 exact matches, discrepancies, evidence and history',async()=>{const root=host(),mounted=presentation.mount(root,{load:()=>model()},{getScope:()=>scope,getActor:()=>actor});assert.equal((await mounted.refresh()).ok,true);const content=text(root);for(const phrase of ['SERVICE_ETP_V1 is isolated from Retail ETP','exact-key match','JOB-001','JOB-002','AMOUNT VARIANCE','Source evidence: s003-row-001','Immutable verification and closure history','EVIDENCE_ADDED','service-proof-001'])assert.match(content,new RegExp(phrase));assert.equal(all(root).some(n=>'innerHTML' in n),false);});

test('first verification stays empty but actionable only for an authorized manager context',async()=>{const root=host(),mounted=presentation.mount(root,{load:()=>model(false),verify:()=>({ok:true})},{getScope:()=>scope,getActor:()=>actor,getActionInput:()=>({operationId:'verify-001',reports:{}})});await mounted.refresh();assert.match(text(root),/ready for first verification/);assert.match(text(root),/No Service ETP verification/);assert.equal(all(root).filter(n=>n.tagName==='BUTTON').length,1);assert.equal(all(root).find(n=>n.tagName==='BUTTON').disabled,false);const staff=host(),staffMount=presentation.mount(staff,{load:()=>model(false),verify:()=>({ok:true})},{getScope:()=>scope,getActor:()=>({actorId:'STAFF-1',role:'Staff'})});await staffMount.refresh();assert.equal(all(staff).find(n=>n.tagName==='BUTTON').disabled,true);assert.equal((await staffMount.verify()).code,'E7_PRESENTATION_ACTION_UNAVAILABLE');});

test('controlled actions receive only live service scope/actor plus bounded provider input and refresh',async()=>{const root=host(),calls=[];let loads=0;const facade={load:()=>{loads++;return model();},verify:r=>{calls.push(['verify',r]);return{ok:true};},addEvidence:r=>{calls.push(['addEvidence',r]);return{ok:true};},close:r=>{calls.push(['close',r]);return{ok:true};}};const mounted=presentation.mount(root,facade,{getScope:()=>scope,getActor:()=>actor,getActionInput:(name,id,runId)=>name==='verify'?{operationId:'verify-002',reports:{S003_REVENUE:{}}}:{eventId:name+'-002',runOperationId:runId,discrepancyId:id,evidenceKind:'SOURCE_CHECK',evidenceReference:'proof-002',closureReasonCode:'VERIFIED_SOURCE'} });await mounted.refresh();const id='verify-001|JOB-002|AMOUNT_VARIANCE';for(const [name,args] of [['verify',[]],['addEvidence',[id,'verify-001']],['close',[id,'verify-001']]])assert.equal((await mounted[name](...args)).ok,true);assert.equal(loads,4);assert.deepEqual(calls.map(x=>x[0]),['verify','addEvidence','close']);for(const [,request] of calls){assert.equal(request.scopeKey,scope.scopeKey);assert.equal(request.actorId,actor.actorId);assert.equal(request.actorRole,'Owner');assert.equal('binding' in request,false);assert.equal('profile' in request,false);}});

test('scope or actor drift fails closed before action and sanitized denial remains retryable',async()=>{let liveScope=scope,liveActor=actor,calls=0;const root=host(),facade={load:()=>model(),verify:()=>{calls++;return{ok:false,code:'private/path'};},addEvidence:()=>({ok:true}),close:()=>({ok:true})},mounted=presentation.mount(root,facade,{getScope:()=>liveScope,getActor:()=>liveActor});await mounted.refresh();assert.equal((await mounted.verify()).code,'E7_PRESENTATION_ACTION_FAILED');assert.doesNotMatch(text(root),/private\/path/);assert.ok(all(root).filter(n=>n.tagName==='BUTTON').length>=1);liveScope={scopeKey:'SERVICE_ETP_V1|SC02|2026-27|2026-08-01..2026-08-31'};assert.equal((await mounted.verify()).code,'E7_PRESENTATION_CONTEXT_CHANGED');assert.equal(calls,1);liveScope=scope;liveActor={actorId:'MANAGER-2',role:'Store Manager'};assert.equal((await mounted.verify()).code,'E7_PRESENTATION_CONTEXT_CHANGED');assert.equal(calls,1);});

test('Retail ETP scope is rejected before facade access',async()=>{let loads=0;const root=host(),mounted=presentation.mount(root,{load:()=>{loads++;return model();}},{getScope:()=>({scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31'}),getActor:()=>actor});const out=await mounted.refresh();assert.equal(out.code,'E7_SERVICE_SCOPE_REQUIRED');assert.equal(loads,0);assert.match(text(root),/Retail ETP scopes are never borrowed/);});

test('rejects malformed model projections and hostile result fields',()=>{const bad=model();bad.state.runs[0].result.matches[0].customerMobile='9999999999';assert.equal(presentation.cleanModel(bad),null);const wrong=model();wrong.boundary='RETAIL_ETP_V1';assert.equal(presentation.cleanModel(wrong),null);const inconsistent=model();inconsistent.state.runs[0].result.summary.matchedCount=9;assert.equal(presentation.cleanModel(inconsistent),null);});

test('source and CSS keep text-only sinks, mobile containment and desktop grid',()=>{const source=fs.readFileSync(new URL('../www/etp-e7-presentation.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../www/etp-e7-presentation.css',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|SaagarNative|Capacitor|window\.parent|parent\.postMessage|document\.(?:querySelector|getElementById)|innerHTML/);assert.match(source,/host\.ownerDocument/);assert.match(source,/textContent/);assert.match(css,/min-height:44px/);assert.match(css,/max-width:100%/);assert.match(css,/minmax\(min\(100%,160px\),1fr\)/);assert.match(css,/@media\(max-width:480px\)/);assert.match(css,/@media\(min-width:900px\)/);assert.doesNotMatch(css,/100vw|overflow-x:\s*auto/);});
