import test from 'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),api=require('../www/etp-e3-orchestrator.js'),engine=require('../www/etp-cro-reconciliation.js'),foundation=require('../www/etp-operational-foundation.js');
const scope={storeCode:'WLMHW',businessDate:'2026-08-24'},bind={scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31',generationId:'etp_'+'a'.repeat(32),receiptId:'receipt-1'};
const actor=(role='Store Manager',at='2026-08-24T10:00:00.000Z',reason='reviewed')=>({actorId:'ACTOR-1',actorRole:role,at,reauthenticatedAt:role==='Staff'?null:at,reason});
function setup(read){let data=new Map,authority=foundation.registerAuthority({domain:'E3',status:'ACTIVE',sourceSha256:'b'.repeat(64),approvalId:'E3-OWNER-2026-08-25-V1',approvedAt:'2026-08-25T00:00:00.000Z',approvedByRole:'Owner',stores:['WLMHW']});let made=api.create({engine,foundation,authority,operationalStore:{load:k=>data.get(k)||null,save:(k,v)=>{data.set(k,v);return true;}},readVerified:read||(request=>({source:'ETP_VERIFIED',scopeKey:request.scopeKey,generationId:request.generationId,receiptId:request.receiptId,rows:[{invoiceId:'I1',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:100,croId:'C1'}]}))});assert.equal(made.ok,true);return{orch:made.orchestrator,data,authority};}
test('fails closed without exact injected dependencies and active hash-bound E3 authority',()=>{assert.equal(api.create({}).code,'E3_DEPENDENCY_UNAVAILABLE');let x=setup(),bad=api.create({engine,foundation,operationalStore:{load(){},save(){}},readVerified(){},authority:{ok:true,authority:{domain:'E3',status:'ACTIVE',sourceSha256:'bad'}}});assert.equal(bad.code,'E3_DEPENDENCY_UNAVAILABLE');assert.ok(Object.isFrozen(x.orch));});
test('runs approved lifecycle, persists across restart and exact verified binding',async()=>{let x=setup(),o=x.orch;assert.equal((await o.open(scope)).ok,true);assert.equal((await o.declare(scope,actor('Staff'),{invoiceId:'I1',croId:'C1',netAmount:100})).ok,true);assert.equal((await o.close(scope,actor())).ok,true);assert.equal((await o.importVerified(scope,actor(),bind)).ok,true);assert.equal((await o.markImported(scope,actor())).ok,true);assert.equal((await o.reconcile(scope,actor())).ok,true);assert.equal((await o.markReconciled(scope,actor(),'RECONCILED')).ok,true);assert.equal((await o.lock(scope,actor())).ok,true);let restarted=setup().orch,record=[...x.data.values()][0];let shared=new Map([['E3|WLMHW|2026-08-24',record]]),made=api.create({engine,foundation,authority:x.authority,operationalStore:{load:k=>shared.get(k)||null,save:(k,v)=>{shared.set(k,v);return true;}},readVerified:()=>{throw Error();}}).orchestrator;assert.equal((await made.load(scope)).day.state,'LOCKED');});
test('privileged calls require fresh grants and store/scope/generation/receipt match exactly',async()=>{let x=setup(()=>({source:'ETP_VERIFIED',...bind,receiptId:'other',rows:[]})),o=x.orch;await o.open(scope);let stale=actor('Store Manager','2026-08-24T10:10:01.000Z');stale.reauthenticatedAt='2026-08-24T10:00:00.000Z';assert.equal((await o.close(scope,stale)).code,'E3_FRESH_GRANT_REQUIRED');await o.close(scope,actor());assert.equal((await o.importVerified(scope,actor(),bind)).code,'E3_VERIFIED_BINDING_INVALID');assert.equal((await o.importVerified(scope,actor(),{...bind,scopeKey:'HEMW|2026-27|2026-08-01..2026-08-31'})).code,'E3_VERIFIED_BINDING_INVALID');});
test('locked state is immutable and restatement starts only a new verified generation cycle',async()=>{let x=setup(),o=x.orch;await o.open(scope);await o.declare(scope,actor('Staff'),{invoiceId:'I1',croId:'C1',netAmount:100});await o.close(scope,actor());await o.importVerified(scope,actor(),bind);await o.markImported(scope,actor());await o.reconcile(scope,actor());await o.markReconciled(scope,actor(),'RECONCILED');await o.lock(scope,actor());assert.equal((await o.correct(scope,actor('Owner'),{invoiceId:'I1',croId:'C2'})).code,'DAY_LOCKED');assert.equal((await o.startRestatementCycle(scope,actor('Owner'),bind)).code,'E3_NEW_GENERATION_REQUIRED');let next={...bind,generationId:'etp_'+'c'.repeat(32),receiptId:'receipt-2'},out=await o.startRestatementCycle(scope,actor('Owner'),next);assert.equal(out.ok,true);assert.equal(out.cycle,2);assert.equal(out.day.state,'CLOSED');assert.equal(out.day.sourceBinding.generationId,next.generationId);});
test('portable backup contains human overlay but never source fact rows',async()=>{let x=setup(),o=x.orch;await o.open(scope);await o.close(scope,actor());await o.importVerified(scope,actor(),bind);let out=await o.createPortableBackup(scope,'2026-08-24T12:00:00.000Z');assert.equal(out.ok,true);let text=JSON.stringify(out.backup);assert.doesNotMatch(text,/sourceFacts|rawRows|workbook|netAmount/);assert.match(text,/ETP_HUMAN_ACTION_OVERLAYS/);});
test('source has no direct browser, native or storage access and remains API23 syntax-safe',()=>{let source=fs.readFileSync(new URL('../www/etp-e3-orchestrator.js',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|document\.|window\.|fetch\s*\(|XMLHttpRequest|async\s*\*|\?\.|\?\?/);});
