import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import intakeContract from '../www/etp-e4-authority-intake.js';
import planning from '../www/etp-target-planning.js';
import foundation from '../www/etp-operational-foundation.js';
import orchestrator from '../www/etp-e4-orchestrator.js';

const scopeKey='WLMHW|2026-27|2026-09-01..2026-09-30';
const sha256=value=>crypto.createHash('sha256').update(value,'utf8').digest('hex');
const api=intakeContract.create({sha256});
const payloads={
  TITAN_TARGET:{targetAuthorityId:'TITAN-FY26-SEP-WLMHW',issuer:'Titan Company Limited',documentRef:'TARGET-WLMHW-2026-09',issuedDate:'2026-08-20',currency:'INR',storeTargetPaise:4000000},
  FESTIVE_CALENDAR:{calendarAuthorityId:'FESTIVE-2026-V1',version:1,entries:[{date:'2026-09-15',multiplierBps:20000,reason:'Approved festive trading day'}]},
  CRO_IDENTITY_MAP:{mapAuthorityId:'CRO-MAP-2026-V1',version:1,mappings:[{croId:'CRO-1',employeeId:'EMP-101',activeFrom:'2026-04-01',activeTo:null},{croId:'CRO-2',employeeId:'EMP-102',activeFrom:'2026-04-01',activeTo:'2027-03-31'}]},
  E4_POLICY_AUTHORITY:{policyAuthorityId:'E4-POLICY-2026-V1',effectiveFrom:'2026-04-01',effectiveTo:'2027-03-31',stretchTargetBps:11000,lyWeighting:'LY_DAILY_ACTUAL',leaveProration:'APPROVED_HALF_FULL_DAY',coverageShortfall:'REDUCE_TARGET_AND_LABEL',allocationLock:'DAY_ZERO',achievementSource:'ETP_VERIFIED_ONLY'}
};
const candidate=type=>({contractVersion:intakeContract.VERSION,sourceType:type,scopeKey,payload:structuredClone(payloads[type])});
function approved(type,c=candidate(type)){const sourceSha256=api.prepareCandidate(c).sourceSha256;return {sourceType:type,status:'APPROVED',sourceSha256,approvalId:'OWNER-'+type+'-001',approvedAt:'2026-08-25T08:00:00Z',approvedByRole:'Owner',approvedBy:'owner-1',storeCode:'WLMHW',scopeKey};}
function packageItems(){const out={};for(const type of intakeContract.SOURCE_TYPES){const c=candidate(type);out[type]=api.validateApprovedCandidate(c,approved(type,c));}return out;}
function memory(){const sources=new Map(),bindings=new Map(),ops=new Map();return {getSourceIntake:k=>sources.get(k),getSourceBinding:k=>bindings.get(k),saveSourceIntake(k,v,m){sources.set(k,v);bindings.set(k,m.value.binding);ops.set(k+'|'+m.operationId,m);},getVersions:()=>[],saveVersion(){},findOperation:(k,id)=>ops.get(k+'|'+id)};}

test('candidate templates are explicit, frozen and remain unapproved/invalid until completed',()=>{for(const type of intakeContract.SOURCE_TYPES){const made=intakeContract.candidateTemplate(type,scopeKey);assert.equal(made.status,'CANDIDATE_UNAPPROVED');assert.equal(Object.isFrozen(made.candidate.payload),true);assert.equal(api.validateApprovedCandidate(made.candidate,{}).code,'E4_SOURCE_SCHEMA_INVALID');}assert.equal(intakeContract.candidateTemplate('UNKNOWN',scopeKey).code,'E4_CANDIDATE_TEMPLATE_SCOPE_INVALID');});

test('all four exact schemas produce deterministic hash-bound owner-reviewed records',()=>{const items=packageItems();for(const type of intakeContract.SOURCE_TYPES){assert.equal(items[type].ok,true);assert.equal(items[type].sourceSha256.length,64);assert.equal(items[type].approval.approvedByRole,'Owner');assert.equal(Object.isFrozen(items[type]),true);}assert.equal(api.readiness(items).status,'READY_FOR_ORCHESTRATOR_INTAKE');});

test('candidate preparation exposes the exact hash for external Owner review without creating approval',()=>{const prepared=api.prepareCandidate(candidate('TITAN_TARGET'));assert.equal(prepared.status,'CANDIDATE_VALIDATED_UNAPPROVED');assert.equal(prepared.sourceSha256.length,64);assert.equal('approval' in prepared,false);assert.equal(Object.isFrozen(prepared.candidate),true);});

test('hash, approval, store and scope mismatches fail closed without minting approval',()=>{const c=candidate('TITAN_TARGET'),a=approved('TITAN_TARGET',c);assert.equal(api.validateApprovedCandidate(c,{...a,sourceSha256:'f'.repeat(64)}).code,'E4_SOURCE_OWNER_APPROVAL_INVALID');assert.equal(api.validateApprovedCandidate(c,{...a,approvedByRole:'Store Manager'}).code,'E4_SOURCE_OWNER_APPROVAL_INVALID');assert.equal(api.validateApprovedCandidate(c,{...a,storeCode:'HEMW'}).code,'E4_SOURCE_OWNER_APPROVAL_INVALID');assert.equal(api.validateApprovedCandidate(c,{...a,scopeKey:scopeKey.replace('WLMHW','HEMW')}).code,'E4_SOURCE_OWNER_APPROVAL_INVALID');});

test('schema extensions, invalid dates, duplicate identities and unapproved policy choices are rejected',()=>{const extra=candidate('TITAN_TARGET');extra.payload.comment='accept anyway';assert.equal(api.validateApprovedCandidate(extra,approved('TITAN_TARGET',extra)).code,'E4_SOURCE_SCHEMA_INVALID');const festiveCandidate=candidate('FESTIVE_CALENDAR');festiveCandidate.payload.entries.push({...festiveCandidate.payload.entries[0]});assert.equal(api.validateApprovedCandidate(festiveCandidate,approved('FESTIVE_CALENDAR',festiveCandidate)).code,'E4_SOURCE_SCHEMA_INVALID');const croCandidate=candidate('CRO_IDENTITY_MAP');croCandidate.payload.mappings[1].employeeId='EMP-101';assert.equal(api.validateApprovedCandidate(croCandidate,approved('CRO_IDENTITY_MAP',croCandidate)).code,'E4_SOURCE_SCHEMA_INVALID');const policyCandidate=candidate('E4_POLICY_AUTHORITY');policyCandidate.payload.leaveProration='UNAPPROVED_FORMULA';assert.equal(api.validateApprovedCandidate(policyCandidate,approved('E4_POLICY_AUTHORITY',policyCandidate)).code,'E4_SOURCE_SCHEMA_INVALID');});

test('readiness enumerates missing/invalid authorities and rejects cross-scope, duplicate hashes or extra package keys',()=>{const partial={TITAN_TARGET:packageItems().TITAN_TARGET};const blocked=api.readiness(partial);assert.equal(blocked.code,'E4_AUTHORITY_PACKAGE_INCOMPLETE');assert.deepEqual(blocked.requirements.map(x=>x.status),['APPROVED','MISSING','MISSING','MISSING']);const items=packageItems();items.FESTIVE_CALENDAR={...items.FESTIVE_CALENDAR,scopeKey:scopeKey.replace('2026-27','2027-28')};assert.equal(api.readiness(items).code,'E4_AUTHORITY_PACKAGE_INVALID');const duplicate=packageItems();duplicate.FESTIVE_CALENDAR={...duplicate.FESTIVE_CALENDAR,sourceSha256:duplicate.TITAN_TARGET.sourceSha256};assert.equal(api.readiness(duplicate).code,'E4_AUTHORITY_PACKAGE_INVALID');const extra=packageItems();extra.UNREVIEWED_SOURCE=extra.TITAN_TARGET;assert.equal(api.readiness(extra).code,'E4_AUTHORITY_PACKAGE_INVALID');});

test('validated package adapts exactly to existing E4 orchestrator source intake',()=>{const converted=api.toOrchestratorSources(packageItems());assert.equal(converted.ok,true);assert.equal(Object.keys(converted.sources).length,4);assert.deepEqual(Object.keys(converted.sources.TITAN_TARGET).sort(),['approvalId','approvedAt','approvedByRole','scopeKey','sourceSha256','sourceType','status','storeCode']);const active=foundation.registerAuthority({domain:'E4',status:'ACTIVE',sourceSha256:'9'.repeat(64),approvalId:'E4-OWNER-001',approvedAt:'2026-08-25T08:00:00Z',approvedByRole:'Owner',stores:['WLMHW']});const e4=orchestrator.create({planning,foundation,store:memory()});const binding={source:'ETP_VERIFIED',scopeKey,generationId:'etp_'+'b'.repeat(32),receiptId:'receipt-e4-authority'};const result=e4.intakeSources({scopeKey,binding,operationId:'source-authority-1',sources:converted.sources,activeAuthority:active,actorId:'owner-1',actorRole:'Owner',at:'2026-08-25T09:04:00Z',reauthenticatedAt:'2026-08-25T09:00:00Z'});assert.equal(result.ok,true);assert.equal(e4.readiness({scopeKey,binding}).ok,true);});

test('canonicalization is key-order stable and mapped identities contain no names or contact fields',()=>{const a=candidate('CRO_IDENTITY_MAP'),b={payload:a.payload,scopeKey:a.scopeKey,sourceType:a.sourceType,contractVersion:a.contractVersion};assert.equal(intakeContract.canonicalize(a),intakeContract.canonicalize(b));const keys=new Set();const visit=value=>{if(Array.isArray(value))return value.forEach(visit);if(value&&typeof value==='object')for(const [key,item] of Object.entries(value)){keys.add(key.toLowerCase());visit(item);}};visit(packageItems());for(const forbidden of ['customer','mobile','phone','email','aadhaar','pan','employeename'])assert.equal(keys.has(forbidden),false);});
