import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import intake from '../www/etp-e5-authority-intake.js';
import money from '../www/etp-incentive-control.js';

const scopeKey='WLMHW|2026-27|2026-07-01..2026-07-31';
const generationId='etp_'+'a'.repeat(32),receiptId='receipt-e5-governed-1';
const sha256=value=>crypto.createHash('sha256').update(value,'utf8').digest('hex');
const authority=intake.create({sha256});
const payloads={
  INCENTIVE_SCHEME:{schemeAuthorityId:'E5-SCHEME-FY26',versionId:'FY26-V1',effectiveFrom:'2026-04-01',effectiveTo:'2027-03-31',currency:'INR',basis:'ETP_VERIFIED_ACHIEVEMENT',bands:[{fromBps:0,toBps:9999,rateBps:0},{fromBps:10000,toBps:10999,rateBps:100},{fromBps:11000,toBps:100000,rateBps:200}],rounding:'NEAREST_PAISE_HALF_UP',eligibility:{reconciliationStatus:'PASS',requireCompleteDays:true,allowVerifiedZero:true},restatementPolicy:'DURABLE_CLAWBACK_ONLY'},
  CRO_PAYROLL_EMPLOYEE_MAP:{mapAuthorityId:'E5-MAP-FY26',versionId:'PAYROLL-MAP-V1',mappings:[{storeCode:'WLMHW',croId:'CRO-1',employeeId:'EMP-101',effectiveFrom:'2026-04-01',effectiveTo:null},{storeCode:'WLMHW',croId:'CRO-2',employeeId:'EMP-102',effectiveFrom:'2026-04-01',effectiveTo:'2027-03-31'}]},
  E5_POLICY_AUTHORITY:{policyAuthorityId:'E5-POLICY-FY26',effectiveFrom:'2026-04-01',effectiveTo:'2027-03-31',unassignedTreatment:'BLOCK',closePlusDays:15,clawbackPeriodPolicy:'NEXT_OPEN_PAYROLL_PERIOD',payrollPrelockPolicy:'OWNER_PRELOCK_REQUIRED',achievementSource:'ETP_VERIFIED_ONLY'}
};
const candidate=type=>({contractVersion:intake.VERSION,sourceType:type,scopeKey,payload:structuredClone(payloads[type])});
function approval(type,c=candidate(type)){return{sourceType:type,status:'APPROVED',sourceSha256:authority.prepareCandidate(c).sourceSha256,approvalId:'OWNER-'+type+'-001',approvedAt:'2026-08-25T08:00:00Z',approvedByRole:'Owner',approvedBy:'OWNER-1',storeCode:'WLMHW',scopeKey};}
function items(){return Object.fromEntries(intake.SOURCE_TYPES.map(type=>{const c=candidate(type);return[type,authority.validateApprovedCandidate(c,approval(type,c))];}));}
function authorityPackage(){return authority.activateApprovedPackage(items()).authorityPackage;}
const base=()=>({authorityPackage:authorityPackage(),verifiedActual:{amount:110025,scopeKey,generationId,receiptId},targetPlan:{amount:100000,approved:true,versionId:'TARGET-V1'},period:'2026-07',croId:'CRO-1',asOfDate:'2026-08-15',run:{source:'ETP_VERIFIED',scopeKey,generationId,receiptId,reconciliationStatus:'PASS',hasGap:false,hasUnassigned:false,days:[{status:'COMPLETE'},{status:'VERIFIED_ZERO'}]}});
const event={contractVersion:'ETP_E6_RESTATEMENT_EVENT_V1',eventId:'RESTATEMENT|'+scopeKey+'|etp_'+'c'.repeat(32),scopeKey,storeCode:'WLMHW',previousGenerationId:generationId,newGenerationId:'etp_'+'c'.repeat(32),occurredAt:'2026-08-16T00:00:00.000Z',ownerId:'OWNER-1',reasonCode:'SOURCE_CORRECTION',evidenceReference:'receipt-restated-1',consumer:'E5_INCENTIVE_CLAWBACK'};

test('all E5 templates remain explicit unapproved candidates and incomplete authority cannot activate',()=>{for(const type of intake.SOURCE_TYPES){const made=intake.candidateTemplate(type,scopeKey);assert.equal(made.status,'CANDIDATE_UNAPPROVED');assert.equal(Object.isFrozen(made.candidate),true);assert.equal(authority.prepareCandidate(made.candidate).code,'E5_SOURCE_SCHEMA_INVALID');assert.equal('approval' in made.candidate,false);}assert.equal(authority.activateApprovedPackage({INCENTIVE_SCHEME:items().INCENTIVE_SCHEME}).code,'E5_AUTHORITY_PACKAGE_INCOMPLETE');});

test('scheme, mapping and policy canonicalize deterministically then require separate hash-bound Owner approval',()=>{const approved=items(),active=authority.activateApprovedPackage(approved);assert.equal(active.status,'APPROVED_HASH_BOUND');assert.equal(active.authorityPackage.status,'ACTIVE');assert.equal(active.authorityPackage.packageSha256.length,64);assert.equal(Object.isFrozen(active.authorityPackage),true);const c=candidate('INCENTIVE_SCHEME'),prepared=authority.prepareCandidate(c);assert.equal(prepared.status,'CANDIDATE_VALIDATED_UNAPPROVED');assert.equal('approval' in prepared,false);assert.equal(authority.validateApprovedCandidate(c,{...approval('INCENTIVE_SCHEME',c),approvedByRole:'Store Manager'}).code,'E5_SOURCE_OWNER_APPROVAL_INVALID');assert.equal(authority.validateApprovedCandidate(c,{...approval('INCENTIVE_SCHEME',c),sourceSha256:'f'.repeat(64)}).code,'E5_SOURCE_OWNER_APPROVAL_INVALID');});

test('exact schemas reject band holes, duplicate Payroll identities and unapproved policy choices',()=>{const schemeCandidate=candidate('INCENTIVE_SCHEME');schemeCandidate.payload.bands[1].fromBps=10001;assert.equal(authority.prepareCandidate(schemeCandidate).code,'E5_SOURCE_SCHEMA_INVALID');const mapCandidate=candidate('CRO_PAYROLL_EMPLOYEE_MAP');mapCandidate.payload.mappings[1].employeeId='EMP-101';assert.equal(authority.prepareCandidate(mapCandidate).code,'E5_SOURCE_SCHEMA_INVALID');const policyCandidate=candidate('E5_POLICY_AUTHORITY');policyCandidate.payload.payrollPrelockPolicy='AUTO_LOCK';assert.equal(authority.prepareCandidate(policyCandidate).code,'E5_SOURCE_SCHEMA_INVALID');const extra=candidate('E5_POLICY_AUTHORITY');extra.payload.silentDefault=true;assert.equal(authority.prepareCandidate(extra).code,'E5_SOURCE_SCHEMA_INVALID');});

test('governed calculation binds verified receipt, exact band edge, approved rounding, mapping and close+15',()=>{const b=base(),atEdge={...b,verifiedActual:{...b.verifiedActual,amount:100000}},before={...b,asOfDate:'2026-08-14'};assert.equal(money.finalize(before).code,'E5_HOLDBACK_OPEN');const final=money.finalize(atEdge).result;assert.equal(final.incentive,1000);assert.equal(final.employeeId,'EMP-101');assert.equal(final.mapVersion,'PAYROLL-MAP-V1');assert.equal(final.policyAuthorityId,'E5-POLICY-FY26');assert.equal(final.authorityPackageSha256,b.authorityPackage.packageSha256);assert.equal(final.source,'ETP_VERIFIED');assert.equal(money.finalize({...b,verifiedActual:{...b.verifiedActual,receiptId:'forged'}}).code,'E5_RUN_BLOCKED');assert.equal(money.finalize({...b,run:{...b.run,hasGap:true}}).code,'E5_RUN_BLOCKED');});

test('runtime rejects tampered governed rounding, mapping or policy instead of trusting a label',()=>{const b=base(),rounding=structuredClone(b.authorityPackage);rounding.scheme.payload.rounding='FLOOR_RUPEE';assert.equal(money.finalize({...b,authorityPackage:rounding}).code,'E5_AUTHORITY_PACKAGE_INVALID');const mapping=structuredClone(b.authorityPackage);mapping.map.payload.mappings=[];assert.equal(money.finalize({...b,authorityPackage:mapping}).code,'E5_AUTHORITY_PACKAGE_INVALID');const policy=structuredClone(b.authorityPackage);policy.policy.payload.closePlusDays=-1;assert.equal(money.finalize({...b,authorityPackage:policy}).code,'E5_AUTHORITY_PACKAGE_INVALID');});

test('Unassigned follows approved policy and declarations never become payment basis',()=>{const b=base(),blocked={...b,run:{...b.run,hasUnassigned:true,unassignedCount:1}};assert.equal(money.finalize(blocked).code,'E5_UNASSIGNED_BLOCKED');const policyCandidate=candidate('E5_POLICY_AUTHORITY');policyCandidate.payload.unassignedTreatment='EXCLUDE_OWNER_DISPOSED';const custom=items();custom.E5_POLICY_AUTHORITY=authority.validateApprovedCandidate(policyCandidate,approval('E5_POLICY_AUTHORITY',policyCandidate));const packageWithDisposal=authority.activateApprovedPackage(custom).authorityPackage;const disposed={...b,authorityPackage:packageWithDisposal,declarations:999999,run:{...b.run,hasUnassigned:true,unassignedCount:1,unassignedDisposition:'OWNER_DISPOSED_EXCLUDED',unassignedEvidenceReference:'owner-disposal-1'}};assert.equal(money.finalize(disposed).result.source,'ETP_VERIFIED');assert.equal(money.finalize({...disposed,run:{...disposed.run,unassignedEvidenceReference:null}}).code,'E5_UNASSIGNED_BLOCKED');});

test('restatement clawback is idempotent, period-controlled and Payroll batch satisfies Sigma identity',()=>{const one=money.finalize(base()).result,two=money.finalize({...base(),croId:'CRO-2',verifiedActual:{...base().verifiedActual,amount:100000}}).result,c1=money.applyRestatement(one,{event,revisedIncentive:1800}).clawback,c2=money.applyRestatement(one,{event,revisedIncentive:1800}).clawback;assert.deepEqual(c1,c2);assert.equal(c1.applyPeriod,'2026-08');assert.equal(c1.clawbackPeriodPolicy,'NEXT_OPEN_PAYROLL_PERIOD');const batch=money.payrollBatch([one,two],{[one.operationId]:[c1],[two.operationId]:[]}).batch;assert.equal(batch.sigma.baseAmount+batch.sigma.clawbackAmount,batch.sigma.amount);assert.equal(batch.lines.reduce((sum,line)=>sum+line.amount,0),batch.sigma.amount);assert.equal(batch.sigma.identity,true);assert.equal(batch.editable,false);assert.equal(batch.recreatable,false);assert.equal(money.payrollBatch([one,one],{[one.operationId]:[]}).code,'E5_PAYROLL_BLOCKED');});

test('money domain remains pure and emits controlled non-editable lines without direct Payroll mutation',()=>{const source=fs.readFileSync(new URL('../www/etp-incentive-control.js',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|indexedDB|SaagarEtpNativeStore|innerHTML|postMessage|PayrollStore|savePayroll|updatePayroll/);const line=money.payrollLine(money.finalize(base()).result,[]).line;assert.equal(line.lineType,'CONTROLLED_ETP_INCENTIVE');assert.equal(line.editable,false);assert.equal(line.recreatable,false);assert.equal(line.preLockGate,'REQUIRED');});
