import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),bridge=require('../www/etp-e5-payroll-bridge.js');
const scopeKey='WLMHW|2026-27|2026-07-01..2026-07-31';
const finalized={contractVersion:'ETP_E5_INCENTIVE_V1',mode:'FINAL',status:'FINALIZED',operationId:'E5-'+'a'.repeat(8),source:'ETP_VERIFIED',scopeKey,generationId:'etp_'+'b'.repeat(32),receiptId:'receipt-verified-1',period:'2026-07',employeeId:'EMP-1',schemeVersion:'FY26-V1',authorityPackageSha256:'c'.repeat(64),incentive:2200};
const clawback={contractVersion:'ETP_E5_INCENTIVE_V1',clawbackId:'E5-CLAW-'+'d'.repeat(8),finalOperationId:finalized.operationId,restatementEventId:'RESTATEMENT-1',amount:-400,original:2200,revised:1800,status:'PENDING_PAYROLL',reason:'ETP_RESTATED_PERIOD',scopeKey};
const policyLine={lineType:'CONTROLLED_ETP_INCENTIVE',editable:false,recreatable:false,sourceOperationId:finalized.operationId,schemeVersion:'FY26-V1',baseAmount:2200,clawbackAmount:-400,amount:1800,preLockGate:'REQUIRED',sumIdentity:true};

test('creates only a non-editable controlled ETP earning line with exact verified lineage',()=>{const out=bridge.createEarningLine({finalized,clawbacks:[clawback],policyLine});assert.equal(out.ok,true);assert.deepEqual(out.line.clawbackIds,[clawback.clawbackId]);assert.equal(out.line.amount,1800);assert.equal(out.line.employeeId,'EMP-1');assert.equal(out.line.basis,'ETP_VERIFIED');assert.equal(out.line.manualEntryAllowed,false);assert.equal(out.line.editable,false);assert.equal(out.line.recreatable,false);assert.equal(Object.isFrozen(out.line),true);});
test('blocks declared/manual basis, generic line shapes, duplicate clawbacks and broken sum identity',()=>{assert.equal(bridge.createEarningLine({finalized:{...finalized,source:'DECLARED'},clawbacks:[],policyLine:{...policyLine,clawbackAmount:0,amount:2200}}).code,'E5_PAYROLL_BRIDGE_BLOCKED');assert.equal(bridge.createEarningLine({finalized,clawbacks:[clawback],policyLine:{...policyLine,lineType:'BONUS'}}).code,'E5_PAYROLL_BRIDGE_BLOCKED');assert.equal(bridge.createEarningLine({finalized,clawbacks:[clawback,clawback],policyLine:{...policyLine,clawbackAmount:-800,amount:1400}}).code,'E5_PAYROLL_BRIDGE_BLOCKED');assert.equal(bridge.createEarningLine({finalized,clawbacks:[clawback],policyLine:{...policyLine,amount:1799}}).code,'E5_PAYROLL_BRIDGE_BLOCKED');});
test('bridge is pure and has no Payroll storage, UI or generic mutation capability',()=>{const source=fs.readFileSync(new URL('../www/etp-e5-payroll-bridge.js',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB|document\.|window\.|innerHTML|fetch\s*\(|XMLHttpRequest|editPayroll|savePayroll|manualLine|generic/i);assert.deepEqual(Object.keys(bridge).sort(),['VERSION','createEarningLine']);});
