import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import hostApi from '../www/etp-operational-module-host.js';

class El{constructor(doc,name){this.ownerDocument=doc;this.name=name;this.children=[];this.attributes={};this.textContent='';this.className='';}get firstChild(){return this.children[0]||null;}appendChild(v){this.children.push(v);return v;}removeChild(v){this.children.splice(this.children.indexOf(v),1);}setAttribute(k,v){this.attributes[k]=String(v);}}
function fixture(){const map={},doc={createElement:name=>new El(doc,name),querySelector:selector=>map[selector]||null};map['[data-etp-phase6h-operations]']=new El(doc,'operations');map['[data-etp-operational-e3]']=new El(doc,'e3');map['[data-etp-operational-e4]']=new El(doc,'e4');map['[data-etp-verified-content]']=new El(doc,'verified');map['[data-action="etp-import-form"]']=new El(doc,'import');map['[data-etp-operational-e6]']=new El(doc,'e6');map['[data-etp-operational-e5]']=new El(doc,'e5');return{doc,map};}
function text(node){return[node.textContent,...node.children.flatMap(text)].join(' ');}
const scope=()=>({scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31',storeCode:'WLMHW',businessDate:'2026-08-25'});
const actor=()=>({actorId:'owner-1',role:'Owner'});

test('mounts the real dedicated E3/E4/E6/E5 roots and starts one governed refresh',async()=>{const f=fixture(),calls=[];const controller={async refresh(){calls.push('refresh');return{ok:true};},destroy(){calls.push('destroy');return{ok:true};}};let received;const out=hostApi.mount({document:f.doc,bridge:{operational:{E3:{load(){}},E4:{load(){}},E6:{load(){}},E5:{load(){}}}},mountApi:{mount(o){received=o;return{ok:true,controller};}},presentations:{e3:{},e4:{},e6:{},e5:{}},getScope:scope,getActor:actor});assert.equal(out.ok,true);assert.equal(await out.ready.then(x=>x.ok),true);assert.deepEqual(calls,['refresh']);for(const name of ['e3','e4','e6','e5']){assert.equal(received.roots[name],f.map['[data-etp-operational-'+name+']']);assert.equal(received.bridge[name].load instanceof Function,true);}});

test('forwards only bounded E4/E6/E5 action-input and scope subscription providers to the mount',()=>{const f=fixture();let received;const input=()=>({operationId:'op-1'}),e6Input=()=>({exceptionId:'exception-1'}),e5Input=()=>({operation:'calculate'}),subscribe=()=>()=>{};const out=hostApi.mount({document:f.doc,bridge:{operational:{E3:{load(){}},E4:{load(){}},E6:{load(){}},E5:{load(){}}},getE4ActionInput:input,getE6ActionInput:e6Input,getE5ActionInput:e5Input,subscribeScopeChange:subscribe},mountApi:{mount(o){received=o;return{ok:true,controller:{refresh:async()=>({ok:true}),destroy:()=>({ok:true})}};}},presentations:{e3:{},e4:{},e6:{},e5:{}},getScope:scope,getActor:actor});assert.equal(out.ok,true);assert.equal(received.bridge.getE4ActionInput,input);assert.equal(received.bridge.getE6ActionInput,e6Input);assert.equal(received.bridge.getE5ActionInput,e5Input);assert.equal(received.bridge.subscribeScopeChange,subscribe);assert.equal('storage' in received.bridge,false);assert.equal('native' in received.bridge,false);});

test('retains import and verified analytics while refreshing and destroying all operational roots',async()=>{const f=fixture(),untouched=['[data-etp-verified-content]','[data-action="etp-import-form"]'];untouched.forEach((key,i)=>f.map[key].appendChild(new El(f.doc,'sentinel-'+i)));const controller={refresh:async()=>({ok:true}),destroy(){for(const name of ['e3','e4','e6','e5'])f.map['[data-etp-operational-'+name+']'].children=[];return{ok:true};}};const out=hostApi.mount({document:f.doc,bridge:{E3:{},E4:{},E6:{},E5:{}},mountApi:{mount:()=>({ok:true,controller})},presentations:{e3:{},e4:{},e6:{},e5:{}},getScope:scope,getActor:actor});await out.ready;out.controller.destroy();untouched.forEach(key=>assert.equal(f.map[key].children.length,1,key));});

test('renders honest text-only blocked states when operational facades are absent',()=>{const f=fixture(),out=hostApi.mount({document:f.doc,bridge:{},mountApi:{mount(){}},presentations:{e3:{},e4:{},e6:{},e5:{}},getScope:scope,getActor:actor});assert.equal(out.code,'ETP_OPERATIONAL_HOST_DEPENDENCY_UNAVAILABLE');for(const name of ['e3','e4','e6','e5'])assert.match(text(f.map['[data-etp-operational-'+name+']']),new RegExp('Operational ETP unavailable Governed '+name.toUpperCase()+' dependencies are unavailable'));assert.equal(f.map['[data-etp-operational-e3]'].children[0].attributes.role,'alert');});

test('fails closed if the bounded mount throws and never fabricates operational data',()=>{const f=fixture(),out=hostApi.mount({document:f.doc,bridge:{E3:{},E4:{},E6:{},E5:{}},mountApi:{mount(){throw new Error('no');}},presentations:{e3:{},e4:{},e6:{},e5:{}},getScope:scope,getActor:actor});assert.equal(out.code,'ETP_OPERATIONAL_HOST_MOUNT_FAILED');for(const name of ['e3','e4','e6','e5'])assert.match(text(f.map['[data-etp-operational-'+name+']']),/mounting failed closed/);});

test('destroy is idempotent and prevents later refresh',async()=>{const f=fixture();let destroyed=0;const out=hostApi.mount({document:f.doc,bridge:{E3:{},E4:{},E6:{},E5:{}},mountApi:{mount:()=>({ok:true,controller:{refresh:async()=>({ok:true}),destroy(){destroyed++;return{ok:true};}}})},presentations:{e3:{},e4:{},e6:{},e5:{}},getScope:scope,getActor:actor});await out.ready;assert.equal(out.controller.destroy().ok,true);assert.equal(out.controller.destroy().idempotent,true);assert.equal(destroyed,1);assert.equal((await out.controller.refresh()).code,'ETP_OPERATIONAL_HOST_DESTROYED');});

test('source stays API23-safe with text-only sinks and no raw, native, parent or storage access',()=>{const source=fs.readFileSync(new URL('../www/etp-operational-module-host.js',import.meta.url),'utf8');assert.match(source,/textContent/);assert.match(source,/createElement/);assert.doesNotMatch(source,/innerHTML|insertAdjacentHTML|outerHTML|localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|window\.parent|parent\.|postMessage|readFacts|readVerified|rawRows|sourceFacts|fetch\s*\(|XMLHttpRequest|\?\.|\?\?/);});

test('composes through the closure-bound shell facade without receiving parent capabilities',async()=>{const f=fixture(),controller={refresh:async()=>({ok:true}),destroy:()=>({ok:true})};let received;const out=await hostApi.compose({document:f.doc,composer:{compose:async value=>{received=value;return{ok:true,controller,status:{E3:'READY_WLMHW'}};}},getScope:scope});assert.equal(out.ok,true);for(const name of ['e3','e4','e6','e5'])assert.equal(received.roots[name],f.map['[data-etp-operational-'+name+']']);assert.deepEqual(Object.keys(received).sort(),['getScope','roots']);assert.equal(out.status.E3,'READY_WLMHW');});

test('composer denial renders bounded blocked states in all operational roots',async()=>{const f=fixture(),out=await hostApi.compose({document:f.doc,composer:{compose:async()=>({ok:false,code:'ETP_SHELL_OWNER_SESSION_REQUIRED'})},getScope:scope});assert.equal(out.code,'ETP_SHELL_OWNER_SESSION_REQUIRED');assert.match(text(f.map['[data-etp-operational-e3]']),/authorized verified WLMHW scope/);assert.match(text(f.map['[data-etp-operational-e4]']),/independent authority/);assert.match(text(f.map['[data-etp-operational-e6]']),/policy authority and verified binding/);assert.match(text(f.map['[data-etp-operational-e5]']),/incentive authority, verified period and controlled Payroll bridge/);});
