import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url),api=require('../www/etp-e3-verified-join.js');
const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-08-01',periodEnd:'2026-08-31'},binding={scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31',generationId:'etp_'+'a'.repeat(32),receiptId:'receipt-1'};
function facade(rowsByReport,modify){let calls=[];return{calls,async queryReport(selected,request){calls.push({selected,request});let rows=rowsByReport[request.reportId]||[],page={scopeKey:binding.scopeKey,generationId:binding.generationId,reportId:request.reportId,rows,hasMore:false,nextCursor:null};return modify?modify(page,request,calls.length):{ok:true,page};}};}
function made(f){let out=api.create({readFacade:f,scope,binding});assert.equal(out.ok,true,out.code);return out.reader;}
test('fails closed without exact governed facade, scope and receipt binding',()=>{assert.equal(api.create({}).code,'E3_JOIN_DEPENDENCY_UNAVAILABLE');let f=facade({});assert.equal(api.create({readFacade:f,scope,binding:{...binding,scopeKey:'HEMW|2026-27|2026-08-01..2026-08-31'}}).code,'E3_JOIN_BINDING_INVALID');});
test('joins invoice grain deterministically, aggregates duplicate R013 items and preserves verified signs',async()=>{let f=facade({R013:[{invoice_date:'2026-08-24',invoice_number:'I2',net_amount:-10,cro_number:'C2'},{invoice_date:'2026-08-24',invoice_number:'I1',net_amount:60,cro_number:'C1'},{invoice_date:'2026-08-24',invoice_number:'I1',net_amount:40,cro_number:'C1'}],R022:[{invoice_date:'2026-08-24',invoice_number:'I2',net_value:-10},{invoice_date:'2026-08-24',invoice_number:'I3',net_value:0},{invoice_date:'2026-08-24',invoice_number:'I1',net_value:100}]}),out=await made(f).loadDay('2026-08-24');assert.equal(out.ok,true);assert.deepEqual(out.envelope.rows,[{invoiceId:'I1',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:100,croId:'C1'},{invoiceId:'I2',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:-10,croId:'C2'},{invoiceId:'I3',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:0,croId:null}]);assert.deepEqual(Object.keys(out.envelope).sort(),['generationId','receiptId','rows','scopeKey','source'].sort());assert.ok(Object.isFrozen(out.envelope.rows));});
test('requests only bounded daily R013/R022 projections through governed facade',async()=>{let f=facade({R013:[],R022:[]});await made(f).loadDay('2026-08-24');assert.equal(f.calls.length,2);assert.deepEqual(f.calls.map(x=>x.request.reportId),['R013','R022']);assert.ok(f.calls.every(x=>x.request.limit===api.PAGE_LIMIT&&x.request.filters.length===1&&x.request.filters[0].value==='2026-08-24'));assert.deepEqual(f.calls[0].request.fields,['invoice_date','invoice_number','net_amount','cro_number']);});
test('CRO conflicts quarantine invoice IDs and R022 duplicates fail closed',async()=>{let conflict=facade({R013:[{invoice_date:'2026-08-24',invoice_number:'I1',net_amount:1,cro_number:'C1'},{invoice_date:'2026-08-24',invoice_number:'I1',net_amount:1,cro_number:'C2'}],R022:[]}),out=await made(conflict).loadDay('2026-08-24');assert.equal(out.code,'E3_JOIN_CRO_CONFLICT');assert.deepEqual(out.quarantine,['I1']);let duplicate=facade({R013:[],R022:[{invoice_date:'2026-08-24',invoice_number:'I1',net_value:1},{invoice_date:'2026-08-24',invoice_number:'I1',net_value:1}]});assert.equal((await made(duplicate).loadDay('2026-08-24')).code,'E3_JOIN_R022_DUPLICATE');});
test('malformed, missing-ID, cross-binding and overflow rows fail closed',async()=>{for(const rows of [{R013:[{invoice_date:'2026-08-24',net_amount:1,cro_number:'C'}],R022:[]},{R013:[],R022:[{invoice_date:'2026-08-24',invoice_number:'I',net_value:900000000000.01}]},{R013:[{invoice_date:'2026-08-24',invoice_number:'I',net_amount:900000000000,cro_number:'C'},{invoice_date:'2026-08-24',invoice_number:'I',net_amount:1,cro_number:'C'}],R022:[]}])assert.equal((await made(facade(rows)).loadDay('2026-08-24')).ok,false);let cross=facade({},page=>({ok:true,page:{...page,generationId:'etp_'+'b'.repeat(32)}}));assert.equal((await made(cross).loadDay('2026-08-24')).code,'E3_JOIN_PAGE_INVALID');});
test('pagination is bounded and cursor loops are rejected',async()=>{let looping=facade({},page=>({ok:true,page:{...page,hasMore:true,nextCursor:'cur_repeat'}}));assert.equal((await made(looping).loadDay('2026-08-24')).code,'E3_JOIN_CURSOR_INVALID');let n=0,finite=facade({},(page,request)=>({ok:true,page:{...page,rows:[],hasMore:n++===0,nextCursor:n===1?'cur_next':null}})),out=await made(finite).loadDay('2026-08-24');assert.equal(out.ok,true);});
test('source is pure, injected and API23-safe with no PII/raw/native/storage/global access',()=>{let source=fs.readFileSync(new URL('../www/etp-e3-verified-join.js',import.meta.url),'utf8');assert.doesNotMatch(source,/customer|mobile|phone|email|address|aadhaar|\bpan\b|rawRows|readFacts|localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|document\.|window\.|fetch\s*\(|XMLHttpRequest|\?\.|\?\?/i);});
