import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import intake from '../www/etp-e6-authority-intake.js';
import monitor from '../www/etp-exception-monitor.js';

const scope={storeCode:'WLMHW',financialYear:'2026-27',periodStart:'2026-08-01',periodEnd:'2026-08-31',scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31'};
const sha256=value=>crypto.createHash('sha256').update(value,'utf8').digest('hex');
const authority=intake.create({sha256});
const map=value=>Object.fromEntries(intake.TYPES.map(type=>[type,value]));
const payload={authorityId:'E6-POLICY-AUG-2026',effectiveFrom:'2026-08-01',effectiveTo:'2026-08-31',thresholds:monitor.DEFAULT_THRESHOLDS,slaByType:map(24),defaultOwnerByType:map('MGR-1'),acknowledgeRoles:['Store Manager','Owner'],reassignRoles:['Owner'],closeRoles:['Owner','Store Manager'],closureReasonCodes:[...intake.CLOSURE_REASON_CODES]};
const candidate=()=>({contractVersion:intake.VERSION,sourceType:intake.SOURCE_TYPE,scopeKey:scope.scopeKey,payload:structuredClone(payload)});
function approval(c=candidate()){const sourceSha256=authority.prepareCandidate(c).sourceSha256;return{sourceType:intake.SOURCE_TYPE,status:'APPROVED',sourceSha256,approvalId:'E6-OWNER-001',approvedAt:'2026-08-23T08:00:00Z',approvedByRole:'Owner',approvedBy:'OWNER-1',storeCode:'WLMHW',scopeKey:scope.scopeKey};}
function policy(){const c=candidate();return authority.activateApprovedCandidate(c,approval(c)).policy;}
const verified={source:'ETP_VERIFIED',scopeKey:scope.scopeKey,generationId:'etp_'+'c'.repeat(32),receiptId:'receipt-e6-1'};
const signals={attributionChanges:[],unassignedTrend:[],croTargets:[],salesConcentration:[],earlyMovement:[],declaredActual:[{croId:'CRO-1',date:'2026-08-24',declaredUnits:12000,actualUnits:10000,evidenceId:'evidence-variance'}],restatements:[]};
function detected(){return monitor.evaluate({scope,asOfDate:'2026-08-24',signals,verified,activePolicy:policy()}).exceptions[0];}
function request(action,overrides={}){return{action,actorId:'MGR-1',actorRole:'Store Manager',at:'2026-08-25T10:04:00.000Z',reauthenticatedAt:'2026-08-25T10:00:00.000Z',scopeKey:scope.scopeKey,generationId:verified.generationId,ownerId:null,closureReasonCode:null,closureNote:null,evidenceReference:'evidence-action-1',...overrides};}

test('E6 exposes exactly the five unresolved authority inputs and templates never self-approve',()=>{assert.deepEqual(intake.AUTHORITY_INPUTS,['SLA_BY_TYPE','DEFAULT_OWNER_BY_TYPE','ACKNOWLEDGE_AUTHORITY','REASSIGN_AUTHORITY','CLOSE_AUTHORITY']);const made=intake.candidateTemplate(scope.scopeKey);assert.equal(made.status,'CANDIDATE_UNAPPROVED');assert.equal(authority.prepareCandidate(made.candidate).code,'E6_POLICY_SCHEMA_INVALID');assert.equal('approval' in made.candidate,false);});

test('exact candidate is deterministic hash-bound, then separately activated by Owner approval',()=>{const c=candidate(),prepared=authority.prepareCandidate(c);assert.equal(prepared.status,'CANDIDATE_VALIDATED_UNAPPROVED');assert.equal(prepared.sourceSha256.length,64);assert.equal(authority.prepareCandidate({payload:c.payload,scopeKey:c.scopeKey,sourceType:c.sourceType,contractVersion:c.contractVersion}).sourceSha256,prepared.sourceSha256);const activated=authority.activateApprovedCandidate(c,approval(c));assert.equal(activated.status,'APPROVED_HASH_BOUND');assert.equal(activated.policy.status,'ACTIVE');assert.equal(activated.policy.approval.approvedByRole,'Owner');assert.equal(Object.isFrozen(activated.policy),true);});

test('schema, hash, scope and non-Owner approvals fail closed without creating policy',()=>{const c=candidate(),a=approval(c);assert.equal(authority.activateApprovedCandidate(c,{...a,sourceSha256:'f'.repeat(64)}).code,'E6_POLICY_OWNER_APPROVAL_INVALID');assert.equal(authority.activateApprovedCandidate(c,{...a,approvedByRole:'Store Manager'}).code,'E6_POLICY_OWNER_APPROVAL_INVALID');assert.equal(authority.activateApprovedCandidate(c,{...a,scopeKey:scope.scopeKey.replace('WLMHW','HEMW')}).code,'E6_POLICY_OWNER_APPROVAL_INVALID');const widened=candidate();widened.payload.extra='silent-default';assert.equal(authority.prepareCandidate(widened).code,'E6_POLICY_SCHEMA_INVALID');const partial=candidate();delete partial.payload.slaByType.RESTATED_PERIOD;assert.equal(authority.prepareCandidate(partial).code,'E6_POLICY_SCHEMA_INVALID');});

test('detection is bound to active authority, verified generation, SLA, default owner and immutable evidence/history',()=>{const item=detected();assert.equal(item.ownerId,'MGR-1');assert.equal(item.generationId,verified.generationId);assert.equal(item.receiptId,verified.receiptId);assert.equal(item.slaHours,24);assert.equal(item.policyAuthorityId,'E6-POLICY-AUG-2026');assert.equal(item.history[0].action,'DETECTED');assert.equal(item.evidenceHistory[0].reference,'evidence-variance');assert.equal(Object.isFrozen(item.evidenceHistory),true);});

test('acknowledge, evidence, reassign and close form a deterministic append-only governed lifecycle',()=>{const active=policy(),open=detected(),ack=monitor.transition(open,request('ACKNOWLEDGE'),active).exception;assert.equal(ack.status,'ACKNOWLEDGED');assert.deepEqual(open.history.map(x=>x.action),['DETECTED']);assert.deepEqual(ack.history.map(x=>x.action),['DETECTED','ACKNOWLEDGE']);const evidenced=monitor.appendEvidence(ack,{actorId:'MGR-1',actorRole:'Store Manager',at:'2026-08-25T10:05:00.000Z',reauthenticatedAt:'2026-08-25T10:00:30.000Z',scopeKey:scope.scopeKey,generationId:verified.generationId,evidenceKind:'SOURCE_RECEIPT',evidenceReference:'receipt-proof-2',note:'Checked source receipt'},active).exception;assert.equal(evidenced.status,'ACKNOWLEDGED');assert.equal(evidenced.evidenceHistory.length,3);const reassigned=monitor.transition(evidenced,request('REASSIGN',{actorId:'OWNER-1',actorRole:'Owner',at:'2026-08-25T10:06:00.000Z',reauthenticatedAt:'2026-08-25T10:02:00.000Z',ownerId:'MGR-2',evidenceReference:'evidence-reassign'}),active).exception;assert.equal(reassigned.ownerId,'MGR-2');const closed=monitor.transition(reassigned,request('CLOSE',{at:'2026-08-25T10:07:00.000Z',reauthenticatedAt:'2026-08-25T10:03:00.000Z',closureReasonCode:'CORRECTED_AND_VERIFIED',closureNote:'Corrected against verified source',evidenceReference:'evidence-close'}),active).exception;assert.equal(closed.status,'CLOSED');assert.equal(closed.history.length,5);assert.equal(closed.evidenceHistory.length,5);assert.equal(monitor.transition(closed,request('ACKNOWLEDGE'),active).code,'ETP_EXCEPTION_CLOSED_IMMUTABLE');});

test('mutations fail closed on stale reauth, unauthorized role, drift and missing evidence',()=>{const active=policy(),item=detected();assert.equal(monitor.transition(item,request('ACKNOWLEDGE',{at:'2026-08-25T10:06:00.001Z'}),active).code,'ETP_EXCEPTION_MUTATION_DENIED');assert.equal(monitor.transition(item,request('REASSIGN',{ownerId:'MGR-2'}),active).code,'ETP_EXCEPTION_MUTATION_DENIED');assert.equal(monitor.transition(item,request('ACKNOWLEDGE',{scopeKey:scope.scopeKey.replace('WLMHW','HEMW')}),active).code,'ETP_EXCEPTION_MUTATION_DENIED');assert.equal(monitor.transition(item,request('ACKNOWLEDGE',{generationId:'etp_'+'d'.repeat(32)}),active).code,'ETP_EXCEPTION_MUTATION_DENIED');assert.equal(monitor.transition(item,request('ACKNOWLEDGE',{evidenceReference:null}),active).code,'ETP_EXCEPTION_EVIDENCE_REQUIRED');assert.equal(monitor.transition(item,request('CLOSE',{closureReasonCode:'UNAPPROVED_REASON',closureNote:'No',evidenceReference:'evidence-close'}),active).code,'ETP_EXCEPTION_CLOSURE_INCOMPLETE');});

test('merge preserves governed ownership and append-only action/evidence histories',()=>{const active=policy(),item=detected(),ack=monitor.transition(item,request('ACKNOWLEDGE'),active).exception,fresh=detected(),merged=monitor.mergeState([ack],[fresh],'2026-08-26').exceptions[0];assert.equal(merged.status,'ACKNOWLEDGED');assert.equal(merged.history.length,2);assert.equal(merged.evidenceHistory.length,2);assert.equal(merged.ownerId,ack.ownerId);});
