import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import operational from '../www/etp-operational-mount.js';

class El{constructor(doc){this.ownerDocument=doc;this.children=[];this.attributes={};this.textContent='';this.className='';}get firstChild(){return this.children[0]||null;}appendChild(v){this.children.push(v);return v;}removeChild(v){this.children.splice(this.children.indexOf(v),1);}setAttribute(k,v){this.attributes[k]=String(v);}}
const doc={createElement:()=>new El(doc)};const roots=()=>({e3:new El(doc),e4:new El(doc),e6:new El(doc),e5:new El(doc)});const content=node=>[node.textContent,...node.children.flatMap(content)].join(' ');
function setup(){
  const calls={e3:[],e4:[],e6:[],e5:[],destroy:0},listeners=[];
  const presentations={e3:{create(options){return {ok:true,controller:{async refresh(){calls.e3.push(options.getScope().storeCode);return {ok:true};},destroy(){calls.destroy++;}}};}},e4:{mount(host,facade,options){return {ok:true,async refresh(){calls.e4.push(options.getScope().storeCode);return {ok:true};}};}},e6:{mount(host,facade,options){return {ok:true,async refresh(){calls.e6.push(options.getScope().storeCode);return {ok:true};}};}},e5:{mount(host,facade,options){return {ok:true,async refresh(){calls.e5.push(options.getScope().storeCode);return {ok:true};}};}}};
  const bridge={e3:{load(){}},e4:{load(){}},e6:{load(){}},e5:{load(){}},subscribeScopeChange(fn){listeners.push(fn);return()=>{listeners.splice(listeners.indexOf(fn),1);};}};
  return {calls,listeners,presentations,bridge};
}
const actor=()=>({actorId:'owner-1',role:'Owner',at:'2026-08-25T10:00:00Z',reauthenticatedAt:'2026-08-25T09:59:00Z'});

test('fails closed and renders safe unavailable states when any governed bridge is missing',()=>{const r=roots(),out=operational.mount({roots:r,bridge:{e3:{}},presentations:{},getScope:()=>({}),getActor:actor});assert.equal(out.code,'ETP_OPERATIONAL_DEPENDENCY_UNAVAILABLE');for(const name of ['e3','e4','e6','e5'])assert.match(content(r[name]),/Operational ETP unavailable/);assert.equal(r.e3.children[0].attributes.role,'alert');});

test('mounts all injected presentations and coordinates cross-scope refresh',async()=>{const env=setup(),r=roots();let selected={storeCode:'WLMHW',businessDate:'2026-08-25',scopeKey:'WLMHW|2026-27|2026-08-01..2026-08-31'};const out=operational.mount({roots:r,bridge:env.bridge,presentations:env.presentations,getScope:()=>selected,getActor:actor});assert.equal(out.ok,true);assert.equal((await out.controller.refresh()).ok,true);selected={...selected,storeCode:'HEMW',scopeKey:'HEMW|2026-27|2026-08-01..2026-08-31'};env.listeners[0]();await new Promise(resolve=>setTimeout(resolve,0));for(const name of ['e3','e4','e6','e5'])assert.deepEqual(env.calls[name],['WLMHW','HEMW']);});

test('refresh is bounded and queues at most one latest scope pass',async()=>{const env=setup(),r=roots();let selected={storeCode:'WLMHW'},release;const wait=new Promise(resolve=>{release=resolve;});env.presentations.e3.create=options=>({ok:true,controller:{async refresh(){env.calls.e3.push(options.getScope().storeCode);if(env.calls.e3.length===1)await wait;return {ok:true};},destroy(){}}});const out=operational.mount({roots:r,bridge:env.bridge,presentations:env.presentations,getScope:()=>selected,getActor:actor}),first=out.controller.refresh();selected={storeCode:'HEMW'};assert.equal((await out.controller.refresh()).code,'ETP_OPERATIONAL_BUSY');assert.equal((await out.controller.refresh()).code,'ETP_OPERATIONAL_BUSY');release();await first;assert.deepEqual(env.calls.e3,['WLMHW','HEMW']);assert.deepEqual(env.calls.e4,['WLMHW','HEMW']);});

test('destroy removes the scope listener, destroys E3 and clears E4/E6/E5 exactly once',async()=>{const env=setup(),r=roots();for(const name of ['e4','e6','e5'])r[name].appendChild(new El(doc));const out=operational.mount({roots:r,bridge:env.bridge,presentations:env.presentations,getScope:()=>({storeCode:'WLMHW'}),getActor:actor});assert.equal(env.listeners.length,1);assert.equal(out.controller.destroy().idempotent,false);assert.equal(out.controller.destroy().idempotent,true);assert.equal(env.listeners.length,0);assert.equal(env.calls.destroy,1);for(const name of ['e4','e6','e5'])assert.equal(r[name].children.length,0);assert.equal((await out.controller.refresh()).code,'ETP_OPERATIONAL_DESTROYED');});

test('E4 action authority remains wholly inside its facade and presentation',()=>{const env=setup(),r=roots();let received;env.presentations.e4.mount=(host,facade,options)=>{received={facade,options};return {ok:true,refresh:async()=>({ok:true})};};operational.mount({roots:r,bridge:env.bridge,presentations:env.presentations,getScope:()=>({storeCode:'WLMHW'}),getActor:()=>({actorId:'staff-1',actorRole:'Staff'})});assert.equal(received.facade,env.bridge.e4);assert.equal(received.options.getActor().role,'Staff');assert.equal('publish' in operational,false);});

test('E6 action authority and action-input provider remain inside the bounded facade/presentation',()=>{const env=setup(),r=roots();let received;const getE6ActionInput=()=>({exceptionId:'exception-1'});env.bridge.getE6ActionInput=getE6ActionInput;env.presentations.e6.mount=(host,facade,options)=>{received={facade,options};return {ok:true,refresh:async()=>({ok:true})};};operational.mount({roots:r,bridge:env.bridge,presentations:env.presentations,getScope:()=>({storeCode:'WLMHW'}),getActor:actor});assert.equal(received.facade,env.bridge.e6);assert.deepEqual(received.options.getActionInput('close','exception-1'),{exceptionId:'exception-1'});assert.equal('close' in operational,false);});

test('E5 money authority and action-input provider remain inside the bounded facade/presentation',()=>{const env=setup(),r=roots();let received;env.bridge.getE5ActionInput=()=>({operation:'calculate'});env.presentations.e5.mount=(host,facade,options)=>{received={facade,options};return {ok:true,refresh:async()=>({ok:true})};};operational.mount({roots:r,bridge:env.bridge,presentations:env.presentations,getScope:()=>({storeCode:'WLMHW'}),getActor:actor});assert.equal(received.facade,env.bridge.e5);assert.deepEqual(received.options.getActionInput('calculate'),{operation:'calculate'});assert.equal('attachPayroll' in operational,false);});

test('source is API23-safe and has no parent, storage, native, raw-fact or unsafe DOM access',()=>{const source=fs.readFileSync(new URL('../www/etp-operational-mount.js',import.meta.url),'utf8');assert.match(source,/textContent/);assert.match(source,/createElement/);assert.doesNotMatch(source,/innerHTML|insertAdjacentHTML|outerHTML|localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|window\.parent|parent\.|postMessage|readFacts|readVerified|rawRows|sourceFacts|fetch\s*\(|XMLHttpRequest|\?\.|\?\?/);});
