import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url);
const gatewayApi=require('../www/etp-operational-gateway.js'),foundation=require('../www/etp-operational-foundation.js'),storeApi=require('../www/etp-operational-store.js'),adapters=require('../www/etp-operational-adapters.js'),e3o=require('../www/etp-e3-orchestrator.js'),e4o=require('../www/etp-e4-orchestrator.js'),e3=require('../www/etp-cro-reconciliation.js'),e4=require('../www/etp-target-planning.js'),e6=require('../www/etp-exception-monitor.js');
const scopeKey='WLMHW|2026-27|2026-08-01..2026-08-31',binding={scopeKey,generationId:'etp_'+'a'.repeat(32),receiptId:'receipt-1'},clock=()=> '2026-08-25T10:00:00.000Z';
const authority=(domain)=>foundation.registerAuthority({domain,status:'ACTIVE',sourceSha256:(domain==='E3'?'a':'b').repeat(64),approvalId:domain+'-OWNER-001',approvedAt:'2026-08-25T08:00:00Z',approvedByRole:'Owner',stores:['WLMHW']});
function setup(extra={}){let store=extra.store||storeApi.create(foundation).store,deps={foundation,operationalStore:store,adapters,e3Orchestrator:e3o,e4Orchestrator:e4o,e3Engine:e3,e4Engine:e4,e6Engine:e6,verifiedFacade:{readE3:q=>({source:'ETP_VERIFIED',scopeKey:q.scopeKey,generationId:q.generationId,receiptId:q.receiptId,rows:[{invoiceId:'I1',storeId:'WLMHW',invoiceDate:'2026-08-24',netAmount:100,croId:'C1'}]})},authorityProvider:(d)=>authority(d),clock,...extra};return{store,gateway:gatewayApi.create(deps).gateway};}
const base=(role='Store Manager')=>({scopeKey,binding,businessDate:'2026-08-24',actorId:'A1',actorRole:role,at:clock(),reauthenticatedAt:role==='Staff'?null:clock(),reason:'reviewed'});
test('fails closed on missing dependencies and authority',async()=>{assert.equal(gatewayApi.create({}).code,'ETP_GATEWAY_DEPENDENCY_UNAVAILABLE');let g=setup({authorityProvider:()=>null}).gateway;assert.equal((await g.E3.open(base())).code,'E3_GATEWAY_AUTHORITY_UNAVAILABLE');assert.equal(g.E4.readiness({scopeKey,binding}).code,'E4_GATEWAY_AUTHORITY_UNAVAILABLE');});
test('E3 narrow facade runs governed lifecycle without exposing verified rows',async()=>{let g=setup().gateway;assert.equal((await g.E3.open(base())).ok,true);assert.equal((await g.E3.declare({...base('Staff'),declaration:{invoiceId:'I1',croId:'C1',netAmount:100}})).ok,true);assert.equal((await g.E3.close(base())).ok,true);let imported=await g.E3.importVerified(base());assert.equal(imported.ok,true);assert.doesNotMatch(JSON.stringify(imported),/sourceFacts|"rows"|operationalStore/);assert.equal((await g.E3.state({...base(),to:'IMPORTED'})).ok,true);assert.equal((await g.E3.reconcile(base())).ok,true);assert.equal((await g.E3.state({...base(),to:'RECONCILED'})).ok,true);assert.equal((await g.E3.lock(base())).ok,true);});
test('cross-store, stale reauth and mismatched verified identity fail closed',async()=>{let g=setup().gateway;assert.equal((await g.E3.open({...base(),scopeKey:'HEMW|2026-27|2026-08-01..2026-08-31'})).code,'E3_GATEWAY_SCOPE_INVALID');await g.E3.open(base());let stale={...base(),at:'2026-08-25T10:10:01Z',reauthenticatedAt:'2026-08-25T10:00:00Z'};assert.equal((await g.E3.close(stale)).code,'E3_FRESH_GRANT_REQUIRED');let bad=setup({verifiedFacade:{readE3:q=>({source:'ETP_VERIFIED',scopeKey:q.scopeKey,generationId:q.generationId,receiptId:'different',rows:[]})}}).gateway;await bad.E3.open(base());await bad.E3.close(base());assert.equal((await bad.E3.importVerified(base())).code,'E3_VERIFIED_BINDING_INVALID');});
test('E4 remains fail closed until all four approved sources exist',()=>{let g=setup().gateway;assert.equal(g.E4.readiness({scopeKey,binding}).code,'E4_APPROVED_SOURCES_REQUIRED');assert.equal(g.E4.intake({...base('Owner'),operationId:'source-1',sources:{}}).code,'E4_APPROVED_SOURCES_REQUIRED');});
test('restore fence blocks both domains until exact rebind',async()=>{let source=setup(),backup;await source.gateway.E3.open(base());backup=source.store.exportPortable('2026-08-25T11:00:00Z').backup;let targetStore=storeApi.create(foundation).store;targetStore.ingestRestore(backup,'2026-08-25T12:00:00Z');let target=setup({store:targetStore}).gateway;assert.equal((await target.E3.importVerified(base())).code,'E3_RESTORE_REIMPORT_REQUIRED');assert.equal(target.E4.readiness({scopeKey,binding}).code,'E4_RESTORE_REIMPORT_REQUIRED');targetStore.rebindVerifiedScope({source:'ETP_VERIFIED',...binding});assert.notEqual((await target.E3.load(base())).code,'E3_RESTORE_REIMPORT_REQUIRED');assert.equal(target.E4.readiness({scopeKey,binding}).code,'E4_APPROVED_SOURCES_REQUIRED');});
test('gateway surface is frozen, narrow, API23-safe and has no raw dependency exposure',()=>{let g=setup().gateway;assert.deepEqual(Object.keys(g).sort(),['E3','E4','E5','E6','VERSION']);assert.ok(Object.isFrozen(g.E3));assert.ok(Object.isFrozen(g.E5));assert.ok(Object.isFrozen(g.E6));assert.equal(g.store,undefined);assert.equal(g.engine,undefined);let source=fs.readFileSync(new URL('../www/etp-operational-gateway.js',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|document\.|window\.|fetch\s*\(|XMLHttpRequest|async\s*\*|\?\.|\?\?/);});
