import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url),api=require('../www/etp-e3-presentation.js');
class El{constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.attributes={};this.listeners={};this.className='';this.textContent='';this.disabled=false;this.value='';this.firstChild=null;}appendChild(x){this.children.push(x);this.firstChild=this.children[0]||null;x.parentNode=this;return x;}removeChild(x){this.children.splice(this.children.indexOf(x),1);this.firstChild=this.children[0]||null;}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]||null;}addEventListener(k,v){this.listeners[k]=v;}removeEventListener(k){delete this.listeners[k];}querySelector(){return null;}}
class Doc{createElement(tag){return new El(tag,this);}}
function text(el){return [el.textContent].concat(el.children.map(text)).join(' ');}function host(){let d=new Doc;return new El('div',d);}
const day={storeId:'WLMHW',businessDate:'2026-08-24',state:'VARIANCE',declarations:[{invoiceId:'I1',croId:'C1',netAmount:100}],outcomes:[{invoiceId:'I1',outcome:'Misattributed',sourceCroId:'C2',declaredCroId:'C1'}],unassignedQueue:['I2'],dispositions:[],audit:[{event:'RECONCILIATION_COMPUTED',role:'Store Manager',at:'2026-08-24T10:00:00.000Z',reason:'reviewed'}]};
test('fails closed without injected governed facade, host and providers',()=>{assert.equal(api.create({}).code,'E3_PRESENTATION_UNAVAILABLE');});
test('mounts unavailable state without inferring clear status',()=>{let h=host(),out=api.create({host:h,facade:{load:async()=>({ok:false,code:'DENIED'})},getScope:()=>({storeCode:'WLMHW',businessDate:'2026-08-24'}),getActor:()=>null});assert.equal(out.ok,true);assert.match(text(h),/Authority unavailable/);assert.match(text(h),/No governed day is loaded/);assert.equal(h.attributes['data-e3-state'],'unavailable');out.controller.destroy();assert.equal(h.children.length,0);});
test('renders mobile card outcomes, unassigned queue, correction, disposition, lock and audit',async()=>{let h=host(),out=api.create({host:h,facade:{load:async()=>({ok:true,day,cycle:1})},getScope:()=>({storeCode:'WLMHW',businessDate:'2026-08-24'}),getActor:()=>({actorId:'M1',actorRole:'Store Manager'})});await out.controller.refresh();let body=text(h);for(let label of ['Misattributed','Invoice I1','I2','Apply correction','Record disposition','Lock day','RECONCILIATION_COMPUTED'])assert.match(body,new RegExp(label));assert.equal(h.attributes['data-e3-state'],'ready');});
test('Owner-only restatement control appears for locked state and staff controls reflect approved roles',async()=>{let locked={...day,state:'LOCKED'},ownerHost=host(),staffHost=host();let owner=api.create({host:ownerHost,facade:{load:async()=>({ok:true,day:locked,cycle:1})},getScope:()=>({storeCode:'WLMHW',businessDate:'2026-08-24'}),getActor:()=>({actorId:'O1',actorRole:'Owner'})});await owner.controller.refresh();assert.match(text(ownerHost),/Start restatement cycle/);assert.match(text(ownerHost),/Locked and immutable/);let staff=api.create({host:staffHost,facade:{load:async()=>({ok:true,day:{...day,state:'OPEN'},cycle:1})},getScope:()=>({storeCode:'WLMHW',businessDate:'2026-08-24'}),getActor:()=>({actorId:'S1',actorRole:'Staff'})});await staff.controller.refresh();let buttons=[];(function walk(x){if(x.tagName==='button')buttons.push(x);x.children.forEach(walk);})(staffHost);assert.equal(buttons.find(x=>x.textContent==='Add declaration').disabled,false);assert.equal(buttons.find(x=>x.textContent==='Close declarations').disabled,true);});
test('source uses safe DOM sinks only and has no storage/native/parent access',()=>{let source=fs.readFileSync(new URL('../www/etp-e3-presentation.js',import.meta.url),'utf8');assert.match(source,/createElement/);assert.match(source,/textContent/);assert.doesNotMatch(source,/innerHTML|insertAdjacentHTML|outerHTML|localStorage|sessionStorage|indexedDB|Capacitor|SaagarEtpNativeStore|window\.parent|parent\.|fetch\s*\(|XMLHttpRequest|\?\.|\?\?/);});
test('CSS is mobile-first, 44px touch-safe and avoids page-level horizontal reliance',()=>{let css=fs.readFileSync(new URL('../www/etp-e3-presentation.css',import.meta.url),'utf8');assert.match(css,/min-height:44px/);assert.match(css,/overflow-x:hidden/);assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/@media\(min-width:700px\)/);assert.doesNotMatch(css,/(?:^|[;{])min-width:\s*[5-9]\d\dpx|overflow-x:auto/);});
