import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import presentation from '../www/etp-e4-presentation.js';

class Node{constructor(doc,tag='div'){this.ownerDocument=doc;this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.disabled=false;this.className='';this.textContent='';}get firstChild(){return this.children[0]||null;}appendChild(v){this.children.push(v);return v;}removeChild(v){this.children.splice(this.children.indexOf(v),1);}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(k,v){this.listeners[k]=v;}}
const document={createElement:tag=>new Node(document,tag)};
function all(node){return [node,...node.children.flatMap(all)];}
function text(node){return all(node).map(n=>n.textContent).filter(Boolean).join(' | ');}
function host(){return new Node(document);}
const scope={scopeKey:'WLMHW|2026-27|2026-09-01..2026-09-04',storeCode:'WLMHW'};
const actor={actorId:'owner-1',role:'Owner'};
const types=['TITAN_TARGET','FESTIVE_CALENDAR','CRO_IDENTITY_MAP','E4_POLICY_AUTHORITY'];
function model(status='READY'){const ready=status==='READY',authorities=types.map((sourceType,i)=>({sourceType,status:ready?'APPROVED':'MISSING',sourceSha256:ready?String(i+1).repeat(64):null}));const version={versionId:'WLMHW|2026-09-01..2026-09-04|v1',version:1,storeCode:'WLMHW',periodStart:'2026-09-01',periodEnd:'2026-09-04',storeTargetPaise:4000000,allocations:[{croId:'CRO-1',baseTargetPaise:2000000,stretchTargetPaise:2200000},{croId:'CRO-2',baseTargetPaise:2000000,stretchTargetPaise:2000000}]};return {ok:true,status,authorities,sourceIntake:{status:ready?'APPROVED_HASH_BOUND':'INCOMPLETE'},versions:ready?[version]:[],activeVersion:ready?version:null,pace:ready?{versionId:version.versionId,cro:[{croId:'CRO-1',monthTargetPaise:2100000,verifiedActualPaise:500000,rupeeGapPaise:1600000,requiredRunRatePaisePerFullDay:800000,projectedLandingPaise:1800000,achievementBps:2381}]}:null,leave:{approvedCount:1},coverageShortfall:{amountPaise:100000},actions:{publish:ready,revise:ready,reallocate:ready}};}

test('renders prominent fail-closed readiness for all four required authorities',async()=>{const root=host(),mounted=presentation.mount(root,{load:async()=>model('BLOCKED')},{getScope:()=>scope,getActor:()=>actor});assert.equal((await mounted.refresh()).ok,true);const content=text(root);for(const type of types)assert.match(content,new RegExp(type.replace(/_/g,' ')));assert.match(content,/fail-closed/);assert.match(content,/Source intake: INCOMPLETE/);for(const button of all(root).filter(n=>n.tagName==='BUTTON'))assert.equal(button.disabled,true);});

test('blocked authority intake stays visibly empty and cannot smuggle operational planning state',async()=>{const blocked=model('BLOCKED'),root=host(),mounted=presentation.mount(root,{load:async()=>blocked},{getScope:()=>scope,getActor:()=>actor});await mounted.refresh();for(const phrase of ['Approved Titan store target','Approved festive calendar','Approved CRO-to-employee identity map','Owner-approved E4 planning policy','verified pace remain unavailable'])assert.match(text(root),new RegExp(phrase));const version=model().activeVersion;for(const mutate of [x=>{x.versions=[version];},x=>{x.activeVersion=version;},x=>{x.pace=model().pace;},x=>{x.actions.publish=true;},x=>{x.sourceIntake.status='APPROVED_HASH_BOUND';}]){const value=model('BLOCKED');mutate(value);assert.equal(presentation.cleanModel(value),null);}});

test('renders immutable versions, allocations, verified pace and Leave shortfall with textContent sinks',async()=>{const root=host(),mounted=presentation.mount(root,{load:async()=>model()},{getScope:()=>scope,getActor:()=>actor});await mounted.refresh();const content=text(root);for(const phrase of ['Immutable version history','Store target','CRO-1','Verified pace, gap, run-rate and landing','Required run-rate','Projected landing','Approved Leave records','Coverage Shortfall'])assert.match(content,new RegExp(phrase));assert.equal(all(root).some(n=>'innerHTML' in n),false);});

test('action controls require READY, Owner and facade permission while backend remains authoritative',async()=>{const root=host();let calls=0;const facade={load:async()=>model(),publish:async request=>{calls++;assert.deepEqual(request.scope,scope);assert.deepEqual(request.actor,actor);return {ok:true};},revise:async()=>({ok:false,code:'BACKEND_DENIED'}),reallocate:async()=>({ok:true})};const mounted=presentation.mount(root,facade,{getScope:()=>scope,getActor:()=>actor,getActionInput:name=>({name})});await mounted.refresh();assert.equal(all(root).filter(n=>n.tagName==='BUTTON').every(n=>!n.disabled),true);assert.equal((await mounted.publish()).ok,true);assert.equal(calls,1);const denied=await mounted.revise();assert.equal(denied.code,'BACKEND_DENIED');assert.match(text(root),/BACKEND_DENIED/);const staff=host(),staffMount=presentation.mount(staff,facade,{getScope:()=>scope,getActor:()=>({actorId:'staff-1',role:'Staff'})});await staffMount.refresh();assert.equal(all(staff).filter(n=>n.tagName==='BUTTON').every(n=>n.disabled),true);assert.equal((await staffMount.publish()).code,'E4_PRESENTATION_ACTION_UNAVAILABLE');});

test('accepts publish, revise and reallocate through bounded inputs and refreshes verified pace after each success',async()=>{const root=host(),seen=[];let loads=0;const facade={load:async()=>{loads++;return model();}};for(const name of ['publish','revise','reallocate'])facade[name]=async request=>{seen.push({name,request});return {ok:true};};const mounted=presentation.mount(root,facade,{getScope:()=>scope,getActor:()=>actor,getActionInput:name=>({operation:name,storeTargetPaise:4000000})});await mounted.refresh();for(const name of ['publish','revise','reallocate'])assert.equal((await mounted[name]()).ok,true);assert.equal(loads,4);assert.deepEqual(seen.map(x=>x.name),['publish','revise','reallocate']);for(const call of seen){assert.deepEqual(call.request.scope,scope);assert.deepEqual(call.request.actor,actor);assert.equal(call.request.input.operation,call.name);}for(const phrase of ['Verified ₹5,000','Gap ₹16,000','Required run-rate ₹8,000','Projected landing ₹18,000','Achievement 23.81%'])assert.match(text(root),new RegExp(phrase));});

test('keeps controls retryable after a sanitized denial and rejects scope or actor drift',async()=>{const root=host();let liveScope=scope,calls=0;const facade={load:async()=>model(),publish:async()=>{calls++;return {ok:false,code:'private/path leaked'};},revise:async()=>({ok:true}),reallocate:async()=>({ok:true})};const mounted=presentation.mount(root,facade,{getScope:()=>liveScope,getActor:()=>actor});await mounted.refresh();const denied=await mounted.publish();assert.equal(denied.code,'E4_PRESENTATION_ACTION_FAILED');assert.doesNotMatch(text(root),/private\/path/);assert.equal(all(root).filter(n=>n.tagName==='BUTTON').length,3);liveScope={...scope,scopeKey:'WLMHW|2026-27|2026-10-01..2026-10-31'};assert.equal((await mounted.publish()).code,'E4_PRESENTATION_CONTEXT_CHANGED');assert.equal(calls,1);assert.match(text(root),/E4_PRESENTATION_CONTEXT_CHANGED/);});

test('provides accessible unavailable, loading and sanitized error states',async()=>{const root=host(),mounted=presentation.mount(root,{load:async()=>{throw new Error('private path');}},{getScope:()=>scope,getActor:()=>actor});assert.match(text(root),/Select an authorized store/);const result=await mounted.refresh();assert.equal(result.code,'E4_PRESENTATION_LOAD_FAILED');assert.match(text(root),/E4_PRESENTATION_LOAD_FAILED/);const state=all(root).find(n=>n.attributes.role==='alert');assert.ok(state);assert.equal(state.attributes['aria-live'],'polite');});

test('source avoids storage, native, parent and global DOM access and CSS enforces mobile-safe geometry',()=>{const source=fs.readFileSync(new URL('../www/etp-e4-presentation.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../www/etp-e4-presentation.css',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|SaagarNative|Capacitor|window\.parent|parent\.postMessage|document\.(?:querySelector|getElementById)|innerHTML/);assert.match(source,/host\.ownerDocument/);assert.match(source,/textContent/);assert.match(css,/min-height:44px/);assert.match(css,/max-width:100%/);assert.match(css,/minmax\(min\(100%,180px\),1fr\)/);assert.match(css,/@media\(max-width:480px\)/);assert.doesNotMatch(css,/100vw|overflow-x:\s*auto/);});

test('rejects READY models with any missing or unbound authority',()=>{const missing=model();missing.authorities[0].status='MISSING';missing.authorities[0].sourceSha256=null;assert.equal(presentation.cleanModel(missing),null);const bad=model();bad.authorities[1].sourceSha256='not-a-hash';assert.equal(presentation.cleanModel(bad),null);});

test('rejects READY source intake that is not approved and hash-bound',()=>{const value=model();value.sourceIntake.status='INCOMPLETE';assert.equal(presentation.cleanModel(value),null);});
