import test from 'node:test';
import assert from 'node:assert/strict';
import planning from '../www/etp-target-planning.js';
import foundation from '../www/etp-operational-foundation.js';
import orchestrator from '../www/etp-e4-orchestrator.js';

const scopeKey='WLMHW|2026-27|2026-09-01..2026-09-04';
const binding={source:'ETP_VERIFIED',scopeKey,generationId:'etp_'+'b'.repeat(32),receiptId:'receipt-e4-1'};
const active=foundation.registerAuthority({domain:'E4',status:'ACTIVE',sourceSha256:'9'.repeat(64),approvalId:'E4-OWNER-001',approvedAt:'2026-08-25T08:00:00Z',approvedByRole:'Owner',stores:['WLMHW']});
const auth={activeAuthority:active,actorId:'owner-1',actorRole:'Owner',at:'2026-08-25T09:04:00Z',reauthenticatedAt:'2026-08-25T09:00:00Z'};
const sourceTypes=['TITAN_TARGET','FESTIVE_CALENDAR','CRO_IDENTITY_MAP','E4_POLICY_AUTHORITY'];
function approvedSources(){const out={};sourceTypes.forEach((type,i)=>{out[type]={sourceType:type,status:'APPROVED',sourceSha256:String(i+1).repeat(64),approvalId:'E4-SOURCE-00'+(i+1),approvedAt:'2026-08-25T08:00:00Z',approvedByRole:'Owner',storeCode:'WLMHW',scopeKey};});return out;}
function memory(){const sources=new Map(),bindings=new Map(),versions=new Map(),ops=new Map();return {getSourceIntake:k=>sources.get(k),getSourceBinding:k=>bindings.get(k),saveSourceIntake(k,v,m){sources.set(k,v);bindings.set(k,m.value.binding);ops.set(k+'|'+m.operationId,m);},getVersions:k=>versions.get(k)||[],saveVersion(k,v,m){versions.set(k,[...(versions.get(k)||[]),v]);ops.set(k+'|'+m.operationId,m);},findOperation:(k,id)=>ops.get(k+'|'+id)};}
const approval=n=>({status:'APPROVED',approvedBy:'owner-1',approvedAt:`2026-08-${n}T10:00:00Z`,authorityRef:`OWNER-E4-${n}`});
function plan(version=1,parent){const days=['2026-09-01','2026-09-02','2026-09-03','2026-09-04'];return {storeCode:'WLMHW',periodStart:days[0],periodEnd:days[3],version,previousVersionId:parent,storeTargetPaise:4000000,allocationLockDate:days[0],source:{documentRef:'TITAN-TARGET-'+version,receivedDate:'2026-08-20',issuer:'Titan Company Limited'},approval:approval('21'),allocations:[{croId:'CRO-1',baseTargetPaise:2000000,stretchTargetPaise:2200000},{croId:'CRO-2',baseTargetPaise:2000000,stretchTargetPaise:2000000}],lyEvidence:{source:'ETP_VERIFIED',coverageComplete:true,periodStart:'2025-09-01',periodEnd:'2025-09-04'},lyDailyActuals:days.map((d,i)=>({planDate:d,lyDate:d.replace('2026-','2025-'),actualPaise:(i+1)*100000})),festiveOverrides:[{date:days[2],version,multiplierBps:20000,reason:'Approved festive trading day',approval:approval('22')}]};}
function setup(){const store=memory(),api=orchestrator.create({planning,foundation,store});return {store,api};}

test('readiness and source intake fail closed until all four hash-bound owner authorities exist',()=>{const {api}=setup();assert.equal(api.readiness({scopeKey,binding}).code,'E4_APPROVED_SOURCES_REQUIRED');const incomplete=approvedSources();delete incomplete.CRO_IDENTITY_MAP;assert.equal(api.intakeSources({...auth,scopeKey,binding,operationId:'source-1',sources:incomplete}).code,'E4_APPROVED_SOURCES_REQUIRED');const result=api.intakeSources({...auth,scopeKey,binding,operationId:'source-1',sources:approvedSources()});assert.equal(result.ok,true);assert.equal(api.readiness({scopeKey,binding}).ok,true);assert.equal(Object.isFrozen(result.intake.sources.TITAN_TARGET),true);});

test('source intake is idempotent and conflicts on changed approved identities',()=>{const {api}=setup(),request={...auth,scopeKey,binding,operationId:'source-1',sources:approvedSources()};assert.equal(api.intakeSources(request).idempotent,false);assert.equal(api.intakeSources(request).idempotent,true);const changed=approvedSources();changed.TITAN_TARGET.sourceSha256='f'.repeat(64);assert.equal(api.intakeSources({...request,sources:changed}).code,'E4_IDEMPOTENCY_CONFLICT');});

test('publication binds exact scope, source hashes, verified generation and receipt',()=>{const {api}=setup();api.intakeSources({...auth,scopeKey,binding,operationId:'source-1',sources:approvedSources()});const result=api.publish({...auth,scopeKey,binding,operationId:'publish-1',planInput:plan()});assert.equal(result.ok,true);assert.equal(result.published.binding.generationId,binding.generationId);assert.equal(result.published.binding.receiptId,binding.receiptId);assert.equal(result.published.version.version,1);assert.equal(Object.keys(result.published.sourceHashes).length,4);assert.equal(api.publish({...auth,scopeKey,binding,operationId:'publish-1',planInput:plan()}).idempotent,true);const wrong=plan();wrong.storeCode='HEMW';assert.equal(api.publish({...auth,scopeKey,binding,operationId:'publish-2',planInput:wrong}).code,'E4_PLAN_SCOPE_MISMATCH');});

test('revise and reallocate require fresh owner authority and sequential immutable versions',()=>{const {api}=setup();api.intakeSources({...auth,scopeKey,binding,operationId:'source-1',sources:approvedSources()});const v1=api.publish({...auth,scopeKey,binding,operationId:'publish-1',planInput:plan()}).published.version;const p2=plan(2,v1.versionId);p2.allocations=[{croId:'CRO-1',baseTargetPaise:1500000,stretchTargetPaise:1700000},{croId:'CRO-2',baseTargetPaise:2500000,stretchTargetPaise:2500000}];assert.equal(api.reallocate({...auth,scopeKey,binding,operationId:'reallocate-2',planInput:p2}).ok,true);const stale={...auth,reauthenticatedAt:'2026-08-25T08:00:00Z'};assert.equal(api.revise({...stale,scopeKey,binding,operationId:'revise-3',planInput:plan(3,'x')}).code,'ETP_FRESH_REAUTH_REQUIRED');});

test('pace accepts only exact verified binding and never declarations as achievement',()=>{const {api}=setup();api.intakeSources({...auth,scopeKey,binding,operationId:'source-1',sources:approvedSources()});const version=api.publish({...auth,scopeKey,binding,operationId:'publish-1',planInput:plan()}).published.version;const request={scopeKey,binding,versionId:version.versionId,asOfDate:'2026-09-02',approvedLeave:[],actuals:{source:'ETP_VERIFIED',coverageComplete:true,verifiedThrough:'2026-09-02',generationId:binding.generationId,receiptId:binding.receiptId,byCro:{'CRO-1':500000,'CRO-2':400000}}};assert.equal(api.pace(request).ok,true);assert.equal(api.pace({...request,declarations:[{croId:'CRO-1',amountPaise:1}]}).code,'E4_DECLARATIONS_NOT_ACHIEVEMENT');assert.equal(api.pace({...request,actuals:{...request.actuals,receiptId:'other'}}).code,'E4_ACTUAL_BINDING_MISMATCH');assert.equal(api.pace({...request,versionId:'other'}).code,'E4_VERSION_BINDING_MISMATCH');});

test('restored overlays remain fenced until exact generation and receipt are rebound',()=>{const {api}=setup();api.intakeSources({...auth,scopeKey,binding,operationId:'source-1',sources:approvedSources()});const backup=foundation.createPortableBackup([{domain:'E4',storeCode:'WLMHW',scopeKey,overlayId:'plan-1',updatedAt:'2026-08-25T10:00:00Z',payload:{state:'ACTIVE'}}],'2026-08-25T10:00:00Z').backup;const restored=foundation.restorePortableBackup(backup,'2026-08-25T11:00:00Z').restored;assert.equal(api.readiness({scopeKey,binding,restored}).code,'E4_RESTORE_REIMPORT_REQUIRED');const rebound=foundation.rebindVerifiedScope(restored,binding).restored;assert.equal(api.readiness({scopeKey,binding,restored:rebound}).ok,true);assert.equal(api.readiness({scopeKey,binding:{...binding,generationId:'etp_'+'c'.repeat(32)},restored:rebound}).code,'E4_RESTORE_REIMPORT_REQUIRED');});
